### ISSUE TITLE
Places autocompletion

### ISSUE THREAD

**Issue by amjd** [dapriett/nativescript-google-maps-sdk#10]
Is it possible to add auto-completion to addresses entered in a text field or search bar like in apps such as Uber, etc? If yes, can you please show an example of how to implement it?

Thanks!

**Comment by dapriett** [comment]
Google provides a Places API, which is separate from the Maps API.  You can follow the apis for Google Places API for [iOS](https://developers.google.com/places/ios-api/?hl=en) & [Android](https://developers.google.com/places/android-api/)

It may be easier for you to look for a node library like this https://www.npmjs.com/package/node-googleplaces - but I haven't tested it with Nativescript

**Comment by tahir-jamil** [comment]
does this work @amjd ?
