### ISSUE TITLE
IOS - Dont center map on markerClick event

### ISSUE THREAD

**Issue by Neferteus** [dapriett/nativescript-google-maps-sdk#101]
Hi, 

I can do it on android with :

this.mapView.gMap.setOnMarkerClickListener(
            new com.google.android.gms.maps.GoogleMap.OnMarkerClickListener({
                onMarkerClick: (gmsMarker) => {
                    /** ....  */
                    return true;
                }
            })
        );

How can do same in IOS with mapViewDidTapMarker ?

**Comment by Yamilquery** [comment]
How did you solve it for IOS?

**Comment by sam0829** [comment]
I am looking for the same thing. @Neferteus Please let us know how did you achieve that for iOS?

**Comment by keithadler** [comment]
-(BOOL)mapView:(GMSMapView *)mapView didTapMarker:(GMSMarker *)marker
{
    // Show the infowindow
    mapView.selectedMarker = marker;
    
    // Animate the view so the marker is centered just like the default behaviour (you can not do this if you just want to show the infowindow)
    GMSCameraPosition *cameraPosition = [GMSCameraPosition cameraWithLatitude:marker.position.latitude
                                                                    longitude:marker.position.longitude
                                                                         zoom:mapView.camera.zoom];
    [mapView animateToCameraPosition:cameraPosition];
    
    // Don't auto center
    return YES;
}
