### ISSUE TITLE
enable zoom to current position

### ISSUE THREAD

**Issue by lukashlobil** [dapriett/nativescript-google-maps-sdk#102]
Hi, Is there a way to enable the button to go to user's location? 
![button](https://cloud.githubusercontent.com/assets/9610365/20835862/06ee95dc-b89d-11e6-892f-2d0af6a183a1.png)

**Comment by Yamilquery** [comment]
It seems that this excellent module does not have good technical support. 👎

**Comment by Yamilquery** [comment]
I found the solution on my own.

You have to use the nativescript-geolocation module.

`import * as applicationSettings from "application-settings";`

You have to enable the Geolaction:
```
if (!geolocation.isEnabled()) {
        geolocation.enableLocationRequest();
    }
```
Then, you can add a floating button on the map and in the tap event, you apply the following:

```
    geolocation.watchLocation(
      function (loc) {
          if (loc) {
              console.log("Received location: " + loc);
              mapView.latitude = loc.latitude;
              mapView.longitude = loc.longitude;
              marker.position = mapsModule.Position.positionFromLatLng(loc.latitude, loc.longitude);
          }
      }, 
      function(e){
          console.log("Error: " + e.message);
      }, 
      {desiredAccuracy: 3, updateDistance: 10, minimumUpdateTime : 1000 * 20}
    );
```

I hope I can help!

**Comment by dapriett** [comment]
You can also check out this https://github.com/dapriett/nativescript-google-maps-sdk/issues/44
