### ISSUE TITLE
How can I use DirectionsService?

### ISSUE THREAD

**Issue by Yamilquery** [dapriett/nativescript-google-maps-sdk#104]
Hi, 

I can not figure out how to access google.map.DirectionsService

I hope you can help me!

**Comment by dapriett** [comment]
There is not directions integration in this library.  You can look at this plugin: https://github.com/EddyVerbruggen/nativescript-directions

**Comment by tahir-jamil** [comment]
but we need to show the directions with in the app 
nativescript directions will open google maps 
please reopen this issue
