### ISSUE TITLE
Resize marker icon

### ISSUE THREAD

**Issue by subhash279** [dapriett/nativescript-google-maps-sdk#112]
Hi,
I am trying to resize the marker icon using width and height properties but it doesn't  change. Is resizing a marker icon possible?

**Comment by salman15** [comment]
Hi, i got a question how can i get this plugin to run the instructions don't seem to work on my computer.

I'm using the android emulator

Thank you!

**Comment by prolink007** [comment]
I am also very interested in this issue. I am unable to resize custom icons for markers.

**Comment by dapriett** [comment]
There are no icon size options in the SDK, but there is probably a way to resize the icon before assigning it to the marker.  May be easier to just include different sizes in your app, and swap them out.

**Comment by elvismercado** [comment]
@dapriett what if you don't know the size of the image and they the come from a url?

**Comment by mfik** [comment]
Did it using the nativescript-bitmap-factory plugin

`
import { http } from "tns-core-modules";
import { MapView, Marker, Position, UISettings } from "nativescript-google-maps-sdk";
import * as BitmapFactory from "nativescript-bitmap-factory";

let marker = new Marker();
marker.position = Position.positionFromLatLng(item.latitude, item.longitude);

let imageUrl = item.markerImage;

/* Get image source from url */
http.getImage(imageUrl).then((imgSrc) => {
    /* Create new empty bitmap with the same width and height */
    let bmp = BitmapFactory.create(
        imgSrc.width,
        imgSrc.height
    );
    
    bmp.dispose((imageBitmap) => {
        /* Set the source of the bitmap */
        imageBitmap.insert(imgSrc);

        /* resize with aspect ratio */
        let newImageBitmap = imageBitmap.resizeMax(48);
        let newImageSrc = newImageBitmap.toImageSource();

        /* Create new image for the icon */
        let iconImage = new Image();
        iconImage.imageSource = newImageSrc;

        /* Bind the new resized image to the icon */
        marker.icon = iconImage;
    });
});
`

**Comment by liamcharmer** [comment]
Bitmap factory no longer works with the latest versions of NativeScript. There is resize() with the ImageSource, however does not currently work with PNG/transparency.
