### ISSUE TITLE
Calling js method onMapReady failed TypeError: com.google.android.gms.maps.GoogleMap.OnCircleClickListener is not a constructor File: "xxx/files/app/tns_modules/nativescript-google-maps-sdk/map-view.js, line: 208, column: 46

### ISSUE THREAD

**Issue by giovannicandido** [dapriett/nativescript-google-maps-sdk#115]
This is happening on a play store alpha application.

Is not happening deploying to the device from USB.

What could cause this problem?

Android 6.0

**Comment by giovannicandido** [comment]
APK is created with **tns build android --release** command

**Comment by giovannicandido** [comment]
More strange, if a copy the release from usb with `adb install my.apk` it works

**Comment by lolporer** [comment]
had the same problem solved after I've updated the google maps api at the sdk manager

**Comment by giovannicandido** [comment]
Thank you @lolporer,

Updating SDK tools fix the problem. I was using the sdk tools recommended by Nativescript installation tutorial.
Now I just need to update the continuous build docker image.
