### ISSUE TITLE
Nativescript google maps sdk cause me xml error.

### ISSUE THREAD

**Issue by AntonisHopkins** [dapriett/nativescript-google-maps-sdk#116]
Okay let me explain you what I noticed. I copied the code and follow the steps : https://www.npmjs.com/package/nativescript-google-maps-sdk. Got an error.. When I try to tns run app (in my code oreven the code of the npmjs.com)it shows me this and then continues the build: C:\Users\Antony\Desktop\Talos\app\views\maps\maps.xml has syntax errors.
error
element parse error: Error: invalid tagName:Page 
@#[line:11,col:2]
error
element parse error: Error: attribute equal must after attrName
@#[line:16,col:5]
fatalError
end tag name: Page is not match the current start tagName:undefined
@#[line:22,col:16]
Same error as in my code too. BTW In my app infos, my app has access to gps and google play and network of device.It just doesn't open the damn map, instead it throws this error when I try it :ERROR:Building UI from XML. @file ///app/views/maps/maps.xml 1:2 >invalid nodeName
File:"/data/data/org.nativescript.Talos/Files/app/tns_modules/ui/builder/builder.js, line:170,column16
Stacktrace:
........................and so on
I don't know why the xml parser throws me this error.

**Comment by saurabhsharma** [comment]
Same issue with me, trying to add Twitterkit
