### ISSUE TITLE
Get Bounds

### ISSUE THREAD

**Issue by randy-johnson** [dapriett/nativescript-google-maps-sdk#117]
Hello,

I am having trouble figuring out how to get the bounds.

In my web app I would do the following:

var lat0 = map.getBounds().getNorthEast().lat();
var lng0 = map.getBounds().getNorthEast().lng();
var lat1 = map.getBounds().getSouthWest().lat();
var lng1 = map.getBounds().getSouthWest().lng();

Thank You,

Randy

**Comment by randy-johnson** [comment]
Anyone?

**Comment by newgerstas** [comment]
I had the same issue. The decision: i forked this project and added folowing lines of code in the file map-view.android.ts line 341 (where camera change event is invoking)

`bounds: {
        northeast: Position.positionFromLatLng(bounds.northeast.latitude, bounds.northeast.longitude),
        southwest: Position.positionFromLatLng(bounds.southwest.latitude, bounds.southwest.longitude)
}`
