### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by rolandorocha** [dapriett/nativescript-google-maps-sdk#12]
Hi,
I use your plugin with Nativescript 1.5.2. In debug mode are excelent but when I build my release version the app crashes.

**Comment by dapriett** [comment]
Android?  Is this the error you getting in [logcat](http://developer.android.com/tools/help/logcat.html): http://stackoverflow.com/questions/34816786/does-google-maps-android-api-work-in-release-mode

Make sure you have a key setup

**Comment by rolandorocha** [comment]
Android... Already works! 
Thank You
