### ISSUE TITLE
MapView is undefined in Angular component

### ISSUE THREAD

**Issue by newgerstas** [dapriett/nativescript-google-maps-sdk#120]
Hi,

I am using MapView in angular template. I have followed all steps as mentioned in the main page of the repository:
1)  `registerElement("MapView", () => MapView);`
2) Added `@ViewChild("MapView") mapView: MapView` to the properties of angular component class
3) Added it to component template 
`<GridLayout>
        <MapView (mapReady)="onMapReady($event)"></MapView>
    </GridLayout>`

The map displays and active. But i can't add markers and other stuff to the map because my this.mapView property is undefined.

Thanks!

**Comment by MichaelSolati** [comment]
Yea, the method described in the doc didn't work for me. Instead, in on the `onMapReady()` function do this...

```
  private onMapReady(args): void {
    this.mapView = args.object;
  }
```

And replace `@ViewChild("MapView") mapView: MapView;` with `private mapView: MapView;`

You should be all set then.

**Comment by newgerstas** [comment]
Yes. It works. Thank you!

**Comment by dreamcatcher-studio** [comment]
Hi MichaelSolati,
Could you please show the entire Nativescript/Angular component? I cant do the 'private mapView: MapView;' part because Telerik Appbuilder keeps telling me that can't find MapView. In fact I cant do a simple: 
import { MapView } from "nativescript-google-maps-sdk" because it cant find "nativescript-google-maps-sdk"

**Comment by merigold** [comment]
Use like this:


` @ViewChild("MapView") mapView: ElementRef;

    //Map events
    onMapReady = (event) => {
        console.log("Map Ready");
    };
  
    get mapView():MapView{
        this._mapView.nativeElement;
    }
`

**Comment by aosi87** [comment]
Thank you @merigold, I completely forgot about setters in Angular, this is a great solution.
