### ISSUE TITLE
Can't Re-Add Polygons in Android

### ISSUE THREAD

**Issue by SittingFox** [dapriett/nativescript-google-maps-sdk#121]
Hi,

I seem to have hit a problem that only exists in Android. If I end up using `addPolygon` on a polygon that was previously added (after removing), the app crashes. I seem to have narrowed down where it "dies".

```
addPolygon(shape: Polygon) {
    shape.loadPoints(); // last time things were good
    shape.android = this.gMap.addPolygon(shape.android); // dies during this
    this._shapes.push(shape);
}
```

I tried playing around with some different things, such as making it use `reloadPoints` instead of `loadPoints` on repeats, but that didn't seem to work.

I think I may try playing with visibility instead, for cases where I think there may be a chance that a shape would get re-added. But I figure this is worth bringing up. I'm guessing something similar would apply to polylines. Not sure about circles or anything else.

**Comment by arcuri1** [comment]
Hi,

Any news on this?
I have the same issue with the Polyline. Calling removeShape() and then adding again the polyline with addPolyline() make the app crash on Android.
It works perfectly fine on iOS

**Comment by dapriett** [comment]
I would recommend not reusing the object after it's been remove.  I'm guessing the android object is no longer valid after a remove:

https://developers.google.com/android/reference/com/google/android/gms/maps/model/Polyline.html#remove()

```
public void remove ()

Removes this polyline from the map. After a polyline has been removed, the behavior of all its methods is undefined.
```

Either use visibility as @SittingFox pointed out, or create a new Polyline object.

**Comment by SittingFox** [comment]
I tried to play with visibility, but I hit other problems. It was like it would work sometimes and others it would just error out.

What I was doing was keeping an array of objects that held different polygons, setup to be a sort of undo/redo system.

Either I botched something that only affected the Android side in visibility or I'll just have to make some easy object-remake system. I think I might just start over, but I'm on a different project now.

**Comment by SBD580** [comment]
That is caused since the `android` property is changed from PolygonOptions (in the constructor) to Polygon (after loading the points - adding to map). A simple solution will be to keep the  `android` property the same and add another property for the existing polygon (for removal).

**Comment by DanLatimer** [comment]
It would be nice if this worked the same as google maps web api where it's fine to re-add
