### ISSUE TITLE
Error when running tns build ios

### ISSUE THREAD

**Issue by shivapersad** [dapriett/nativescript-google-maps-sdk#122]
I am getting the following error message when I attempt to build my application using the plugin:

JS ERROR ReferenceError: Can't find variable: GMSMapViewDelegate

I have pods installed and it has downloaded and installed the google-maps-sdk pod. I am also using the nativescript-geolocation plugin. I have deleted the contents of my node_modules folder and also removed the ios platform and reinstated both but no luck. I have looked at closed issues for a solution to the issue but I have not found any. Looking forward to your assistance.

**Comment by cgowez** [comment]
Hi, I'm getting the same issue, I'm using nativescript with angular (typescript), cocoapods is installed properly, tns doctor looks good, I see on https://github.com/dapriett/nativescript-google-maps-sdk there are map-view.X.ts files and those are not in my project once I added the plugin with tns plugin add nativescript-google-maps-sdk, so not sure if I have to replace those files under node_modules/nativescript-google-maps-sdk. 
This is happening only on iOS, it is working on android, thanks for your help

**Comment by dapriett** [comment]
Missing GMSMapViewDelegate would mean issues with the Pod install.  Hopefully you have resolved it by now, if not reopen.
