### ISSUE TITLE
Adding marker from Modaldialog callback

### ISSUE THREAD

**Issue by perkka124** [dapriett/nativescript-google-maps-sdk#124]
Hi!
I'm stuck with an issue in my application which is hard to demo. I'm adding a marker from within the resulting callback from a modal dialog. After doing this, moving to other pages produces blank screens and when I return back to the page containing the map, that screen is blank as well (I can see that the mapReady function is called in my log).
I will try get time to create a demo for this. But just wanted to check if someone have had this issue already? Or maybe I'm doing something I'm not supposed to do.

**Comment by dapriett** [comment]
Hopefully you resolved this by now, if not reopen the issue.  If you have a sample app, that would be helpful.
