### ISSUE TITLE
Navigation to maps always crashes app

### ISSUE THREAD

**Issue by ryuker16** [dapriett/nativescript-google-maps-sdk#125]
Whenever I try to navigate to different pages of my app with the map view, I get "Calling on js method onMapReady" failed.

**Comment by ryuker16** [comment]
turns out it's an issue with list view: 

and gmaps possibly related to android ID. This guy solved it:

https://github.com/NativeScript/NativeScript/issues/3595

**Comment by dapriett** [comment]
Hopefully this was resolved, if not reopen the issue. If you have a sample app, that would be helpful.
