### ISSUE TITLE
Marker custom image is not working 

### ISSUE THREAD

**Issue by muralimallow** [dapriett/nativescript-google-maps-sdk#126]
this.mapView = event.object;
      let marker = new Marker();
      marker.position = Position.positionFromLatLng(-33.86, 151.20);
      marker.title = "Sydney";
      marker.snippet = "Austraia";
      var icon = new Image();
      icon.imageSource = imageSource.fromResource('pin');
      marker.icon = icon;

Adding the custom image is not working its through the error in android and ios

**Comment by ryuker16** [comment]
It needs to be converted to a bitmap first.

It's requirement from google so you'll want to convert the map icons to size relevant ones for each platform

**Comment by gizm0bill** [comment]
how do you convert it to bitmap?
