### ISSUE TITLE
Compile time errors. Android and Ios types are not found.

### ISSUE THREAD

**Issue by newgerstas** [dapriett/nativescript-google-maps-sdk#127]
Hi,

I have forked the project and during compile time I get a bunch of errors like:
- Cannot find name 'com' 
- Cannot find name 'java' 
- and same for Ios

I know that these names are specific for certain platform and will be resolved at run time. But these errors are just annoying and inconvenient to see real errors.

One of the solution could be adding NativeScript module called [tns-platform-delarations](https://www.npmjs.com/package/tns-platform-declarations) . It resolves a lot of names at compile time.

Thank you!

**Comment by dapriett** [comment]
These errors should be resolved not.
