### ISSUE TITLE
Map marker difficult to drag

### ISSUE THREAD

**Issue by sm1ddy** [dapriett/nativescript-google-maps-sdk#133]
Hi

Thanks for the great plugin.

I did notice that the map marker requires a very precise touch in order to activate dragging functionality (at least on iOS). Is there anyway to make the marker easier to select?

**Comment by dapriett** [comment]
@sm1ddy - unfortunately I'm not aware of any other settings in the sdk for tuning dragging.

**Comment by liamcharmer** [comment]
Has there been anything on this? I can't even get the marker to drag for some reason.
