### ISSUE TITLE
onCoordinateTapped for touched area?

### ISSUE THREAD

**Issue by sm1ddy** [dapriett/nativescript-google-maps-sdk#134]
Hi

Thanks again for the great plugin.

Is it possible for onCoordinateTapped events to return a value within the specific touched area? This is opposed to just giving the view's overall coordinates.

**Comment by dapriett** [comment]
hi @sm1ddy - the SDKs just return the coordinate that was touched.  If you trying to look up what's at the location, maybe try querying the Google Places api with the coordinate.
