### ISSUE TITLE
iOS Key Declaration and Angular/Webpack Issue

### ISSUE THREAD

**Issue by ShawnPavel** [dapriett/nativescript-google-maps-sdk#136]
I recently implemented webpack in my NNG application that uses the google maps sdk. Previously I had no issues building/releasing my app for both Android and iOS. 

After implementing webpack, my app immediately crashed in iOS. After investigating, I discovered that having the `GMSServices.provideAPIKey` call in the main.ts (as the documentation states) caused the app to crash when the map loads. After moving it to the app.module.ts it all works well. 

I was able to easily reproduce this by creating a new NNG application, adding the plugins for map and webpack, settings the ios api key in main.ts, and executing `npm run start-ios-bundle`.

Essentially, the only requirement is to change the documentation to says `app.module.ts` instead of `main.ts` to prevent users from potentially placing it in the wrong location.

**Comment by dalvarado909** [comment]
Exact same issue and this fixed it! Running latest Nativescript, Angular 4, and webpack, according to the Nativescript docs. My app starts fine to a home screen, when I navigate to my map, I get a Segmentation fault 11. Moving the code you mention to app.module.ts fixes it and my app runs 100% fine again. Thanks!

**Comment by dapriett** [comment]
Thanks for reporting - docs and demo are updated
