### ISSUE TITLE
NS 3.0 - Make the necessary changes to adopt the new version

### ISSUE THREAD

**Issue by jacargentina** [dapriett/nativescript-google-maps-sdk#141]
I'm trying to migrate my app from v 2.5.2 to v 3.0.0.rc and it seems this plugin must the adapted to some changes on NS 3.0.rc

May be there is some other branch for testing it, i would love to test.

**Comment by SamuelGRwebfab** [comment]
any updated info on this? I am also trying to use 3.0 with this plugin and it is giving me some errors.

like this one

`JS: ERROR Error: Uncaught (in promise): TypeError: Could not load view for: MapV
iew.Error: * @deprecated use 'ui/core/properties' module instead.`

**Comment by 3rror404** [comment]
+1. Need this urgently

**Comment by bgildson** [comment]
working on it... maybe today I will to do the PR

**Comment by dapriett** [comment]
Thanks for the PR @bgildson!
