### ISSUE TITLE
How to use google maps geometry library

### ISSUE THREAD

**Issue by jsagar92** [dapriett/nativescript-google-maps-sdk#145]
Hello ,
I am trying to calculate area using google maps geometry library.
But I am not able to use it.
Can any one help.
Is this support provided by plugin or not?
Because I didn't get anything or any issues related to this.

Thanks in advance.

**Comment by dapriett** [comment]
There's no support in this sdk directly, but I'm sure you can include the android and ios libraries yourself in your app.  I'm sure though you can find a javascript library to support what you need as here.  Here are a few I saw from a quick search:

https://www.npmjs.com/package/spherical

https://www.npmjs.com/package/d3-geo
