### ISSUE TITLE
rename MapView#removeAllMarkers to MapView#clear

### ISSUE THREAD

**Issue by naderio** [dapriett/nativescript-google-maps-sdk#15]
According to [docs](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html#clear()) `public final void clear ()` "Removes all **markers**, **polylines**, **polygons**, **overlays**, etc from the map." not just markers.

**Comment by dapriett** [comment]
Changed removeAllMarkers to just remove markers.  Added clear method for removing everything.

**Comment by giorgi-abashidze** [comment]
@dapriett  can you show me an example hwo to remove all markers from map?

**Comment by matiasvilches** [comment]
mapView.removeAllMarkers();
