### ISSUE TITLE
how to use clearAllCircles function

### ISSUE THREAD

**Issue by jatins52** [dapriett/nativescript-google-maps-sdk#150]
Hello all,
greetings to all,

I need little help using for clearing all circles and removing and creating new marker on location change.

Attached zip file contains ts file and corresponding xml file
[code.zip](https://github.com/dapriett/nativescript-google-maps-sdk/files/978258/code.zip)
. 

I need to clear all circles on click of a button in status bar. Also I need to understand how I use other functions from native sdk for maps.

Thanx in advance for help

**Comment by dapriett** [comment]
You can't get the mapView object this way

```
export function clearAllCircles(args) {
    let mapView = args.object;
    // I need to clear all circles here
    mapView.removeAllCircles();
}
```

It's available in the mapReady event - just move the variable outside of it so your other methods can access it.

```
let mapView = null;

export function onMapReady(args) {
   mapView = args.object;
}

export function clearAllCircles(args) {
    mapView.removeAllCircles();
}
```
