### ISSUE TITLE
nativeView get owner undefined on iOS

### ISSUE THREAD

**Issue by edoardocavazza** [dapriett/nativescript-google-maps-sdk#153]
My app on iOS crashes because cannot resolve the `_owner` property of the map delegate implementation on `mapViewIdleAtCameraPosition`:

```
file:///app/tns_modules/nativescript-google-maps-sdk/map-view.js:28:32: JS ERROR TypeError: undefined
is not an object (evaluating 'this._owner.get')
```

The funny thing is that if I console.log the property on `initNativeView` all works as expected.

**Comment by dapriett** [comment]
@edoardocavazza See if the latest version works for you - reopen if not.

**Comment by edoardocavazza** [comment]
No fortune. Sometimes I get that error yet :(

**Comment by leonardo42i** [comment]
Same problem here :(
version 2.1.1
