### ISSUE TITLE
Can not find @string/nativescript_google_maps_api_key

### ISSUE THREAD

**Issue by echap** [dapriett/nativescript-google-maps-sdk#155]
Hello there, since updating tns to version  `2.5.5`, I can't compile the app with the error :

`AndroidManifest.xml:42:28-68: AAPT: No resource found that matches the given name (at 'value' with value '@string/nativescript_google_maps_api_key').`

Any idea why ? It was running fine before {N} 3.0.0 release was published.

Edit : It was a configuration mistake I made on plugging my app back on track ! Sorry about that

**Comment by ZionInc** [comment]
@echap  I am facing the same problem.  What exactly fixed the issue ? (the config you talked about)

**Comment by ZionInc** [comment]
After made following changes and its working now:

1. I had to add `App_Resources\Android\values\strings.xml` .
```
 <resources>
    <string name="nativescript_google_maps_api_key">MY_API_KEY</string>
</resources>
```
2. Cap googlePlayservice version in `App_Resources\Android\app.gradle`
```
android {  
  ......
  project.ext {
    googlePlayServicesVersion = "11.2.2"
  }
} 
```

3. Add `App_Resources\Android\nativescript_google_maps_api.xml` as described in orignal documentation.
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="nativescript_google_maps_api_key">MY_API_KEY</string>
</resources>
```
