### ISSUE TITLE
IOS padding exception

### ISSUE THREAD

**Issue by kvindasAB** [dapriett/nativescript-google-maps-sdk#159]
NS with Angular.

When setting padding via template I get the following.

CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1091:24: ERROR Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'this.gMap.padding = UIEdgeInsetsMake(this.padding[0] || 0, this.padding[2] || 0, this.padding[1] || 0, this.padding[3] || 0)')
	updatePadding@file:///app/tns_modules/nativescript-google-maps-sdk/map-view.js:155:22
	onPaddingPropertyChanged@file:///app/tns_modules/nativescript-google-maps-sdk/map-view-common.js:12:26
	set@file:///app/tns_modules/tns-core-modules/ui/core/properties/properties.js:82:37
	setPropertyInternal@file:///app/tns_modules/nativescript-angular/view-util.js:192:17
	setProperty@file:///app/tns_modules/nativescript-angular/view-util.js:155:37
	setAttribute@file:///app/tns_modules/nativescript-angular/renderer.js:126:41
	setAttribute@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:13383:35
	createElement@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:9378:34
	createViewNodes@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:12051:57
	callViewAction@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:12537:28
	execComponentViewsAction@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:12446:27
	createViewNodes@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:12120:29
	createRootView@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:11998:20
	callWithDebugContext@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:13213:47
	create@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:9919:60
	createComponent@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:10121:68
	loadWithFactory@file:///app/tns_modules/nativescript-angular/common/detached-loader.js:38:49
	activateOnGoForward@file:///app/tns_modules/nativescript-angular/router/page-router-outlet.js:167:75
	activateWith@file:///app/tns_modules/nativescript-angular/router/page-router-outlet.js:139:37
	placeComponentIntoOutlet@file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4526:28
	activateRoutes@file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4507:50
	file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4443:72
	forEach@[native code]
	activateChildRoutes@file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4443:36
	activate@file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4417:33
	file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4034:30
	file:///app/tns_modules/rxjs/Observable.js:107:25
	__tryOrSetError@file:///app/tns_modules/rxjs/Subscriber.js:243:20
	next@file:///app/tns_modules/rxjs/Subscriber.js:185:42
	_next@file:///app/tns_modules/rxjs/Subscriber.js:125:30
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
	_next@file:///app/tns_modules/rxjs/operator/map.js:83:30
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
	notifyNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:143:34
	_next@file:///app/tns_modules/rxjs/InnerSubscriber.js:23:31
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
	_next@file:///app/tns_modules/rxjs/operator/map.js:83:30
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
	_subscribe@file:///app/tns_modules/rxjs/observable/ScalarObservable.js:49:28
	_trySubscribe@file:///app/tns_modules/rxjs/Observable.js:57:35
	subscribe@file:///app/tns_modules/rxjs/Observable.js:45:40
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26
	_innerSub@file:///app/tns_modules/rxjs/operator/mergeMap.js:130:55
	_tryNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:127:23
	_next@file:///app/tns_modules/rxjs/operator/mergeMap.js:110:26
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
	notifyNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:143:34
	_next@file:///app/tns_modules/rxjs/InnerSubscriber.js:23:31
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
	_next@file:///app/tns_modules/rxjs/operator/map.js:83:30
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
	_complete@file:///app/tns_modules/rxjs/operator/reduce.js:119:34
	complete@file:///app/tns_modules/rxjs/Subscriber.js:114:27
	_complete@file:///app/tns_modules/rxjs/operator/mergeMap.js:135:38
	complete@file:///app/tns_modules/rxjs/Subscriber.js:114:27
	_subscribe@file:///app/tns_modules/rxjs/observable/ArrayObservable.js:116:32
	_trySubscribe@file:///app/tns_modules/rxjs/Observable.js:57:35
	subscribe@file:///app/tns_modules/rxjs/Observable.js:45:40
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26
	_innerSub@file:///app/tns_modules/rxjs/operator/mergeMap.js:130:55
	_tryNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:127:23
	_next@file:///app/tns_modules/rxjs/operator/mergeMap.js:110:26
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
	notifyNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:143:34
	_next@file:///app/tns_modules/rxjs/InnerSubscriber.js:23:31
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
	_next@file:///app/tns_modules/rxjs/operator/map.js:83:30
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
	notifyNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:143:34
	_next@file:///app/tns_modules/rxjs/InnerSubscriber.js:23:31
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
	notifyComplete@file:///app/tns_modules/rxjs/operator/every.js:53:30
	_complete@file:///app/tns_modules/rxjs/operator/every.js:70:28
	complete@file:///app/tns_modules/rxjs/Subscriber.js:114:27
	_complete@file:///app/tns_modules/rxjs/operator/mergeMap.js:135:38
	complete@file:///app/tns_modules/rxjs/Subscriber.js:114:27
	_subscribe@file:///app/tns_modules/rxjs/observable/ArrayObservable.js:116:32
	_trySubscribe@file:///app/tns_modules/rxjs/Observable.js:57:35
	subscribe@file:///app/tns_modules/rxjs/Observable.js:45:40
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26
	_innerSub@file:///app/tns_modules/rxjs/operator/mergeMap.js:130:55
	_tryNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:127:23
	_next@file:///app/tns_modules/rxjs/operator/mergeMap.js:110:26
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
	notifyComplete@file:///app/tns_modules/rxjs/operator/every.js:53:30
	_complete@file:///app/tns_modules/rxjs/operator/every.js:70:28
	complete@file:///app/tns_modules/rxjs/Subscriber.js:114:27
	_complete@file:///app/tns_modules/rxjs/operator/mergeMap.js:135:38
	complete@file:///app/tns_modules/rxjs/Subscriber.js:114:27
	_subscribe@file:///app/tns_modules/rxjs/observable/ArrayObservable.js:116:32
	_trySubscribe@file:///app/tns_modules/rxjs/Observable.js:57:35
	subscribe@file:///app/tns_modules/rxjs/Observable.js:45:40
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26
	_innerSub@file:///app/tns_modules/rxjs/operator/mergeMap.js:130:55
	_tryNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:127:23
	_next@file:///app/tns_modules/rxjs/operator/mergeMap.js:110:26
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
	_next@file:///app/tns_modules/rxjs/operator/map.js:83:30
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
	notifyNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:143:34
	_next@file:///app/tns_modules/rxjs/InnerSubscriber.js:23:31
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
	_next@file:///app/tns_modules/rxjs/operator/map.js:83:30
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
	_subscribe@file:///app/tns_modules/rxjs/observable/ScalarObservable.js:49:28
	_trySubscribe@file:///app/tns_modules/rxjs/Observable.js:57:35
	subscribe@file:///app/tns_modules/rxjs/Observable.js:45:40
	subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26
	_innerSub@file:///app/tns_modules/rxjs/operator/mergeMap.js:130:55
	_tryNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:127:23

**Comment by dapriett** [comment]
@kvindasAB - hopefully the latest version 2.0.4 works for you, if not reopen.
