### ISSUE TITLE
zooming on ios?

### ISSUE THREAD

**Issue by tfsmag** [dapriett/nativescript-google-maps-sdk#16]
Great job on this plugin. I am having trouble figuring out how to zoom in ios? 

I can get the map and markers to come up in the emulator and on my devices, just can't seem to figure out how to get the map to zoom in on a certain spot. I've tried gMap.animatetozoom(n) and a couple of other things but can't seem to figure out the syntax. Is there a sample somewhere I haven't found for this? Any help would be greatly appreciated.

**Comment by dapriett** [comment]
You can update the zoom by binding it in the xml view

```
<maps:mapView latitude="{{ latitude }}" longitude="{{ longitude }}" 
                                    zoom="{{ zoom }}" bearing="{{ bearing }}" 
                                    tilt="{{ tilt }}" mapReady="OnMapReady"  
                                markerSelect="onMarkerSelect" 
                                cameraChanged="onCameraChanged" />
```

Could also just do `mapView.zoom = n` in javascript

**Comment by tfsmag** [comment]
hmmm, still doesn't seem to be working for me. I'm sure I'm missing something simple here. I tried putting this in my main-page.js

I set it right after declaring the mapview variable and the map just sits there fully zoomed out.

function onMapReady(args) {
    console.log("onMapReady");
    var mapView = args.object;
    mapView.zoom = 10;

    console.log(args.object);
    console.log("Setting a marker...");

    var marker = new mapsModule.Marker();
    marker.position = mapsModule.Position.positionFromLatLng(-33.86, 151.20);
    marker.title = "Sydney";
    marker.snippet = "Australia";
    marker.userData = { index : 1};
    mapView.addMarker(marker);

    marker = new mapsModule.Marker();
    marker.position = mapsModule.Position.positionFromLatLng(-33.42, 151.32);
    marker.title = "Gosford";
    marker.snippet = "Australia";
    var icon = new Image();
    icon.imageSource = imageSource.fromResource('icon');
    marker.icon = icon;
    // marker.icon = 'icon';
    marker.alpha = 0.8;
    marker.flat = true;
    marker.draggable = true;
    marker.visible = false;
    marker.userData = { index : 2};
    mapView.addMarker(marker);

    

}

I'll keep goofing around with it, can't seem to find any clues in the logging in my terminal window.

**Comment by dapriett** [comment]
I added an example of zooming in the demo app

https://github.com/dapriett/nativescript-google-maps-sdk/blob/master/demo/app/main-page.js#L57

**Comment by tfsmag** [comment]
that worked! thank you very much.
