### ISSUE TITLE
zoom property of viewmodel gets lost

### ISSUE THREAD

**Issue by nicHoch** [dapriett/nativescript-google-maps-sdk#163]
Hi @dapriett thanks for your very helpful plugin unfortunately is has a bug after the NS 3.0 updates in my and in your demo application as well:

the zoom property of the viewModel-Observable gets lost if the map is zoomed by the user.

if you add a zoom log into the CameraChanged method:

```
function onCameraChanged(args) {
    console.log("Camera changed: "+JSON.stringify(args.camera), JSON.stringify(args.camera) === lastCamera);
    console.log("Zoom: ", vmModule.mainViewModel.get("zoom"));
    lastCamera = JSON.stringify(args.camera);
}
```
you can see the current zoom value while panning the map. if you zoom in or out. the property gets lost.

**Comment by dapriett** [comment]
There looks like there was a bug in android - zoom/tilt/bearing were incorrectly being updated.  Should be good now.
