### ISSUE TITLE
[Android][Angular 2] MapView exception with 2.1.0

### ISSUE THREAD

**Issue by ADjenkov** [dapriett/nativescript-google-maps-sdk#166]
Hi,
It's me again. I've updated to 2.1.0 (from completely working 2.0.7) this morning and an exception was thrown:

"JS: ERROR Error: Uncaught (in promise): TypeError: Could not load view for: MapView.Error: com.tns.NativeScriptException: Failed to find module: "nativescript-google-maps-sdk", relative to: app/tns_modules/'

The scenario is the same as I've described here https://github.com/dapriett/nativescript-google-maps-sdk/issues/164
Should I update something else also?

Thanks

**Comment by dapriett** [comment]
Try 2.1.1 - looks like the js files didn't get published to npm
