### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by johndavedecano** [dapriett/nativescript-google-maps-sdk#17]
I use your default instruction.
![screenshot-web facebook com 2016-03-26 04-00-58](https://cloud.githubusercontent.com/assets/1860038/14052756/82fc3776-f307-11e5-8000-58e38514d04c.png)
 I was wondering why this happen[](url)

**Comment by kaliestrawhat** [comment]
I had the same error and removing \plataforms\android\build\intermediates\classes worked for me, google :buildMetadata first though, I did it because it was a throwaway project.

**Comment by VsevolodAstanov** [comment]
This error happen because you missed [this](https://github.com/dapriett/nativescript-google-maps-sdk#setup-android-api-key) step. Folder "Android in the "app/App_Rosources/Android" must include folder "values" with "nativescript_google_maps_api.xml" file. See the description.
