### ISSUE TITLE
setViewport example

### ISSUE THREAD

**Issue by EstebanErcole** [dapriett/nativescript-google-maps-sdk#175]
Hi guys,

I need to set the Viewport, but i'm having a hard time. Always drops an error related to the arguments type like this:

error TS2345: Argument of type '{ northeast: { "latitude": number; "longitude": number; "ios": number; "android": number; }; sout...' is not assignable to parameter of type 'Bounds'.
  
Anyone has an implementation example? 

Thanks!!

**Comment by dapriett** [comment]
Updated demo with an example:

https://github.com/dapriett/nativescript-google-maps-sdk/blob/master/demo/app/main-page.js#L198

**Comment by EstebanErcole** [comment]
Thanks a lot @dapriett, much appreciated!
