### ISSUE TITLE
Getting the below error done with all the steps and while running app getting error

### ISSUE THREAD

**Issue by JaganJonnala** [dapriett/nativescript-google-maps-sdk#178]
![image](https://user-images.githubusercontent.com/10844009/27385596-e0b5108c-56b0-11e7-8424-725c2c38dae7.png)

**Comment by JaganJonnala** [comment]
Can any one Help me out from this

**Comment by dapriett** [comment]
That looks like an error with [nativescript-plugin-firebase](https://github.com/EddyVerbruggen/nativescript-plugin-firebase), not this plugin.

Possibly you don't have the latest Android Google Play services SDK installed, or you're having a version conflict with another plugin using the gradle plugin  [com.google.gms.google-services](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/platforms/android/include.gradle#L54)
