### ISSUE TITLE
99% of map is grey

### ISSUE THREAD

**Issue by dklinzing** [dapriett/nativescript-google-maps-sdk#18]
Was able to run the demo code to run using the android emulator, but for some reason like 99% of the map is grey and a small sliver at the bottom loads.  It seems to load everything, but only a small portion of the map is visible.  I've attached a screenshot.  Any idea what's going on?  
![googlemap-issue](https://cloud.githubusercontent.com/assets/10469057/14149531/934867c6-f672-11e5-96e7-12fa72adecdd.png)

**Comment by dklinzing** [comment]
Nevermind, looks like it's an issue with the map on the emulator.  I ran it on my phone and it's working.

**Comment by dapriett** [comment]
Hi @dklinzing - it should work with emulators as well as long as it has Google Play Services.  I've tested it with using Genymotion emulators.

There is a known issue with Android 4.2.2 - https://github.com/dapriett/nativescript-google-maps-sdk/issues/7

**Comment by dklinzing** [comment]
May be something specifically w/ the emulator I was using.  I was having trouble w/ the AVD emulators that come w/ the Android SDK.  I had Google Play Services installed and it was running Android 6.0 (API 23) on the Google APIs Intel x86 Atom_64 System Image emulator
