### ISSUE TITLE
Icon Marker Color

### ISSUE THREAD

**Issue by mrdeleon** [dapriett/nativescript-google-maps-sdk#180]
Hello, it doesn't looks like there is a way to change the icon color without having to use an image. Do you think that that feature can get added in?

```
static final LatLng MELBOURNE = new LatLng(-37.813, 144.962);
Marker melbourne = mMap.addMarker(new MarkerOptions()
                          .position(MELBOURNE)
                          .icon(BitmapDescriptorFactory.defaultMarker(float hue));
```

I copied that from here in the google api docs

https://developers.google.com/android/reference/com/google/android/gms/maps/model/BitmapDescriptorFactory

Thank you for this plugin.

**Comment by dapriett** [comment]
Try version `2.3.0` - added a `marker.color` field;

Can do any of the following:

Set by color name: `marker.color = 'green';`
Set by hue: `marker.color = 240;`

**Comment by mrdeleon** [comment]
Awesome!

**Comment by jonathanhendra** [comment]
Can we use icon string like this?
marker.icon = "~logo.png"
