### ISSUE TITLE
Could not find module

### ISSUE THREAD

**Issue by Mflm** [dapriett/nativescript-google-maps-sdk#187]
I get this error message:

ERROR Error: Could not find module 'tns-core-modules/ui/core/properties'. Computed path '/Users/franlaz/Library/Developer/CoreSimulator/Devices/08887377-2ACB-4849-8A10-32408FDA49BC/data/Containers/Bundle/Application/94249FAC-5A35-43CB-BE26-8B230726DF6F/Utile.app/app/tns_modules/tns-core-modules/ui/core/properties'.
Jul  4 14:37:54 MacBook-Air-de-Marco com.apple.CoreSimulator.SimDevice.08887377-2ACB-4849-8A10-32408FDA49BC.launchd_sim[10865] (UIKitApplication:com.rsk.Utile[0x3af5][14283]): Service exited due to signal: Segmentation fault: 11

**Comment by dapriett** [comment]
Then Nativescript is not properly installed - `'tns-core-modules/ui/core/properties` is part of their package.  Maybe try removing your `node_modules` and `platform` folders, and reinstalling.
