### ISSUE TITLE
iOS Build Error on Telerik Platform

### ISSUE THREAD

**Issue by dklinzing** [dapriett/nativescript-google-maps-sdk#19]
Getting the following error on the Telerik Platform when trying to build a project using the google maps sdk module.  We removed the module and the app built ok.  Do you have any idea why this might be?

Error: Cannot build project because module nativescript-google-maps-sdk contains insecure code. Remove the module and try again.

**Comment by dapriett** [comment]
I'm not experienced with the Telerik Platform - found the [nativescript-sqlite](https://github.com/NathanaelA/nativescript-sqlite) plugin had the same issue https://github.com/NathanaelA/nativescript-sqlite/issues/4

@teobugslayer - any ideas?

**Comment by dklinzing** [comment]
Thanks for your help, @dapriett.  I'll submit a support ticket too through their ticketing portal.  Hopefully it's an easy fix on their end.

-Dan

**Comment by dklinzing** [comment]
FYI - got this from Telerik

The issue is due to the usage of Cocoapods in the above mentioned plugin. This is so, because for such plugins Telerik Platform checks if their authors are among the trusted ones for our organization. This is something that will change in the future. 

This said, I have now escalated this to our development team in order to add dapriett as a trusted {N} plugin developer. Once this is done, you will be able to use the google maps plugin in AppBuilder

**Comment by dapriett** [comment]
Great, thanks for contacting them and for the update!

**Comment by dklinzing** [comment]
This works now.  

-Dan
