### ISSUE TITLE
Map not loading

### ISSUE THREAD

**Issue by bonlemuel** [dapriett/nativescript-google-maps-sdk#191]
Hi. Great plugin! But I have an issue. Map fired. Events are fired. But the map is not showing. Any way to debug? Thanks!

**Comment by Robophil** [comment]
I'm facing this same issue currently

**Comment by bonlemuel** [comment]
Hi @Robophil were you able to make it work?

**Comment by Robophil** [comment]
I was @bonlemuel. The issue was with my google map api key. Go down to https://console.developers.google.com/apis/dashboard and do the following.
1. Click on **Enable api**
2. Click on **Google map android api**
3. Click on Enable, then you're good to go.

**Comment by bonlemuel** [comment]
Hi @Robophil . Yup. I got it working last night. :) I also realized that I did not activate the Google API itself. Thank you so much for your assistance.
