### ISSUE TITLE
Android marker icon

### ISSUE THREAD

**Issue by MMacku** [dapriett/nativescript-google-maps-sdk#20]
Hi, when i try add icon to marker i get following error:

`TypeError: Cannot read property 'android' of null
File: "/data/data/app.test.test/files/app/tns_modules/nativescript-google-maps-sdk/map-view.js, line: 311, column: 115`

I have images placed right in AppResource file (in xml element Image is normal showed).

**Comment by dapriett** [comment]
Thanks - I pulled in your fix
