### ISSUE TITLE
Multiline marker title + snippet

### ISSUE THREAD

**Issue by Nurgunkalol** [dapriett/nativescript-google-maps-sdk#200]
Hello, i  want to add lines for my text on title and snippet, how i can do this?

**Comment by mast3rd3mon** [comment]
any progress on this yet?

**Comment by EstebanErcole** [comment]
Perhaps you already try this: 

`\n`

that worked for me.-

**Comment by mast3rd3mon** [comment]
yeah, ive tried `\n`, `&#x000A;` as well as html tags

**Comment by dapriett** [comment]
Just added the ability for custom info windows - you can try that out (see README)

**Comment by mast3rd3mon** [comment]
How do you write it in html though? The sample is xml

**Comment by dapriett** [comment]
You could try this: [https://docs.nativescript.org/cookbook/ui/html-view](https://docs.nativescript.org/cookbook/ui/html-view)

**Comment by mast3rd3mon** [comment]
How will that help? I'm on about the info windows

**Comment by culunvb** [comment]
I Just try with used /n but nothing happens in snippet.

**Comment by culunvb** [comment]
\n thats I mean

**Comment by mast3rd3mon** [comment]
@dapriett Any progress on this (despite it being closed) seen as though the custom info windows dont load. All that gets displayed is what is set from `marker.title` and `marker.snippet`

**Comment by DavidMares22** [comment]
you can just add new properties  "markers[i].congestion,  markers[i].distance"

and then you display the data in a infoWindowTemplate..............

 mapView.infoWindowTemplate = <StackLayout orientation="vertical" width="200" height="150" >
    
                      <Label text="{{congestion}}" className="title" width="200"   />
                      <Label text="{{distance}}" className="title" width="200"   />
