### ISSUE TITLE
file:///app/tns_modules/nativescript-google-maps-sdk/map-view.js:168:83: JS ERROR Error: Now use instance.nativeView instead of instance.ios

### ISSUE THREAD

**Issue by wiliarko** [dapriett/nativescript-google-maps-sdk#207]
file:///app/tns_modules/nativescript-google-maps-sdk/map-view.js:168:83: JS ERROR Error: Now use instance.nativeView instead of instance.ios

how i solve it ?

**Comment by dapriett** [comment]
hello @wiliarko - please use .nativeView vs .ios from the mapView object.
