### ISSUE TITLE
Map moving / resetting data.

### ISSUE THREAD

**Issue by randy-johnson** [dapriett/nativescript-google-maps-sdk#214]
Hello,

I need some advice.  I have my map set up to connect to the server and get an updated set of pins based the bounds of the map.

This works great.   The issue I am having is that when I click on an icon to show the info window the map automatically re-centers itself to show the info window in the middle of the screen.

When that happens the map icons refresh and closes the info window because the bounds of the map changed.

I had a thought of setting a variable when info window tapped and if that variable was true then do not refresh the icons.  But to do that I would have to be able to know when the info window is closed.

Sort of like an onInfoWindowClose function.

I did find this:
https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnInfoWindowCloseListener

Would it be hard to implement this function?

Also is there a different way to handle my dilemma?  

Thank You,

**Comment by dapriett** [comment]
Maybe try modifying your logic to reuse markers returned from the server that are already on the map, and not removing them.  I'm guessing you're clearing the map, and recreating them all?

**Comment by randy-johnson** [comment]
Yes, that is correct.  At the moment I am removing them all and recreating.

**Comment by dapriett** [comment]
Not sure how much data you're displaying, but may even be better performance only add/removing what is different then currently displaying.  Something like this maybe...

`
import * as _ from 'lodash';

var newDataIds = _.map(dataFromServer, 'id'); // extract 
var markersToRemove = _.filter(markers, marker => !_.contains(newDataIds, marker.userData.id) );
var dataToAdd = _.filter(dataFromServer, data => _.contains(newDataIds, data.id) );

_.each(markersToRemove, marker => map.removeMarker(marker));

// Add dataToAdd here...
`

**Comment by randy-johnson** [comment]
Not much data at the moment, but I think that will be a better way to go because it should stop the issue I am seeing. I will give it a whirl.

Thank you for your prompt responses.
