### ISSUE TITLE
How to get current zoom level on iOS

### ISSUE THREAD

**Issue by dvdbrk** [dapriett/nativescript-google-maps-sdk#225]
I am struggling to understand how to deal with Objective C with Nativescript. Any ideas how to get the current zoom level of the map? Maybe there is some built in method, but I am interested in using ```GMSCameraPosition``` and its zoom property - for the sake of understanding how to access native iOS layer.

**Comment by dapriett** [comment]
hello @dvdbrk - this file would be a good place to look at for understanding how we deal with iOS: https://github.com/dapriett/nativescript-google-maps-sdk/blob/master/map-view.ios.ts#L84

`mapView.nativeView` should give you access to the native iOS map.  Then look this for api docs:

https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_map_view?hl=vi

I'll admit, I primarily do JS & JAVA dev, but I get by with the Objective C.  Your best bet is asking the nativescript community:  http://developer.telerik.com/wp-login.php?action=slack-invitation
