### ISSUE TITLE
coordinateTapped args.position has no postion

### ISSUE THREAD

**Issue by Imdapro** [dapriett/nativescript-google-maps-sdk#230]
Hey!

I have a problem with _coordinateTapped_ event.  The position property has only one child: '_android', but no latitude or longitude. Everything else works fine except this. I'm using angular 2.

My template: 
<pre>
&lt;StackLayout&gt;<br />
&nbsp;&nbsp; &nbsp;&lt;MapView class=&quot;map-view&quot; #mapView (mapReady)=&quot;onMapReady($event)&quot; (coordinateTapped)=&quot;coordinateTapped($event)&quot;&gt;&lt;/MapView&gt;<br />
&lt;/StackLayout&gt;
</pre>

My callback function:
<pre>coordinateTapped(args) { 
        Object.keys(args.position).forEach((key) =>{
            console.log('key ', key);
        });
// only output is 'key  _android'
} </pre>

Do you have any idea for the solution?

Thanks a lot,
Mark

**Comment by jeffswitzer** [comment]
Mark, this is working for me on android using 

- tns 3.3
- angular 4.4.1
- "nativescript-google-maps-sdk": "^2.4.2"

```
(coordinateTapped)="onCoordinateTapped($event)"

onCoordinateTapped = (args) => {
        console.log("Coordinate Tapped, Lat: " + args.position.latitude + ", Lon: " + args.position.longitude, args);
}
```

example output on a tap
`JS: Coordinate Tapped, Lat: 39.52528333583745, Lon: -96.22051142156124 [object Object]`

**Comment by dapriett** [comment]
`Object.keys` wouldn't work anyways, since it's a getter (not an actual key).  You can look here for fields:

https://github.com/dapriett/nativescript-google-maps-sdk/blob/master/map-view.android.ts#L583
