### ISSUE TITLE
Custom markers not working on IOS

### ISSUE THREAD

**Issue by yenjcc** [dapriett/nativescript-google-maps-sdk#234]
I follow the demo example  and it's works for Android but in iOS keeps showing default google maps Marker... any suggest?

```

var imgScr = new ImageSource();
imgScr.fromResource('icon');
var icon = new Image();
icon.imageSource =  imgScr; 
marker.icon = icon;


mapview.addMarker(marker);
```

**Comment by yenjcc** [comment]
Ok, i solved this problem, if you gonna use an icon from sources (App Source folder) just do this: marker.icon =  'name_of_icon'.  This works for me.  :)

**Comment by TheOnlyMatt** [comment]
Hello,

When I execute your code, I have an error 
```
app/shared/modals/map-modal/map-modal.component.ts(130,9): error TS2322: Type 'HTMLImageElement' is not assignable to type 'string | Image'.
  Type 'HTMLImageElement' is not assignable to type 'Image'.
    Property 'android' is missing in type 'HTMLImageElement'.
```

Here is my function : 
```
    private addUserMarker(){

        var imgScr = new ImageSource();
        imgScr.fromResource('user-position');
        var icon = new Image();
        icon.src =  imgScr;

        var marker = new Marker()
        marker.position = Position.positionFromLatLng(this.userInfo.geolocation.latitude, this.userInfo.geolocation.longitude)
        marker.icon = icon;
        this.mapView.nativeElement.addMarker(marker)
    }
```

I also imported the image souce : 
const ImageSource = require("image-source");

Have you done something specific to convert the HTMLImageElement to string | Html ?

**Comment by yenjcc** [comment]
No, you dont need  imgScr, just do this:

        var marker = new Marker()
        marker.position = Position.positionFromLatLng(this.userInfo.geolocation.latitude, 
        this.userInfo.geolocation.longitude)
        marker.icon = 'user-position';
        this.mapView.nativeElement.addMarker(marker)
