### ISSUE TITLE
When setting latitude and longitude at runtime the map center isn't correct

### ISSUE THREAD

**Issue by pvcoelho** [dapriett/nativescript-google-maps-sdk#239]
I'm setting latitude and longitude values at runtime at OnInit, but the map isn't centered correctly (it is centered at 0º Latitude and 0º Longitude).
I've tried using mapView.updateCamera() but it doesn't refresh the position.
I'm also setting a marker with same latitude and latitude values and this is displayed correctly on the map, so my variables have the correct values (I've also checked with console.log).
Nevertheless, if the latitude and longitude are set at the declaration in the class, the map is centerd well.

Here's map.component.ts:

`
import { Component, ElementRef, ViewChild, OnInit } from '@angular/core';

import { registerElement } from 'nativescript-angular/element-registry';
import { MapView, Marker, Position, latitudeProperty } from 'nativescript-google-maps-sdk';

// Important - must register MapView plugin in order to use in Angular templates
registerElement("MapView", () => require("nativescript-google-maps-sdk").MapView);

import { ActivatedRoute } from "@angular/router";

@Component({
  moduleId: module.id,
  selector: 'app-map',
  templateUrl: './map.component.html',
  styleUrls: ['./map.component.css']
})
export class MapComponent implements OnInit {

  //latitude =  38.735231; //Map is centered correctly if uncommented
  //longitude = -9.146986; //Map is centered correctly if uncommented
  latitude: number;   //Initialized in ngOnInit()!
  longitude: number;  //Initialized in ngOnInit()!

  zoom = 17;
  bearing = 0;
  tilt = 0;
  padding = [40, 40, 40, 40];
  mapView: MapView;

  lastCamera: String;

  constructor(private route: ActivatedRoute, ) {
  }

  ngOnInit() {
    this.latitude = this.route.snapshot.params["lat"];
    this.longitude = this.route.snapshot.params["lon"];
    console.log("1- Lat: " + this.latitude + ", Lon: " + this.longitude); //OK!
  }

  //Map events
  onMapReady(event) {
    console.log('Map Ready');

    this.mapView = event.object;

    console.log("2- Lat: " + this.latitude + ", Lon: " + this.longitude); //OK!

    this.mapView.updateCamera(); //NOT working!!!

    console.log("Setting a marker...");

    var marker = new Marker();
    marker.position = Position.positionFromLatLng(this.latitude, this.longitude);
    marker.title = "JLD Saldanha";
    marker.snippet = "Av. Duque D'Avila, n°46C 1050-053 Lisboa";
    marker.userData = { index: 1 };
    this.mapView.addMarker(marker);
    marker.showInfoWindow();

  }

  onCoordinateTapped(args) {
    console.log("Coordinate Tapped, Lat: " + args.position.latitude + ", Lon: " + args.position.longitude, args);
  }

  onMarkerEvent(args) {
    console.log("Marker Event: '" + args.eventName
      + "' triggered on: " + args.marker.title
      + ", Lat: " + args.marker.position.latitude + ", Lon: " + args.marker.position.longitude, args);
  }

  onCameraChanged(args) {
    console.log("Camera changed: " + JSON.stringify(args.camera), JSON.stringify(args.camera) === this.lastCamera);
    this.lastCamera = JSON.stringify(args.camera);
  }

}
`

**Comment by yenjcc** [comment]
Try to set the latitude and longitude in the mapView Object
```
onMapReady(event) {
this.mapView.latitude = this.latitude;
this.mapView.longitude= this.longitude;
}
```

**Comment by pvcoelho** [comment]
Hi yenjcc,

Thanks for the tip but unfortunately the map isn't centered accordingly to the new values.
In addition, checking the console output shows:

"JS: 1- Lat: 38.735231, Lon: -9.146986
JS: Map Ready
JS: 2- Lat: 38.735231, Lon: -9.146986
JS: Setting a marker...
JS: Camera changed: {"latitude":0,"longitude":0,"zoom":17,"bearing":0,"tilt":0} false".

So even though the global variables have the correct values (output lines 1 and 3) the camera isn't updating accordingly (output line 5).

Heres the final code for OnInit and onMapReady:

    `  ngOnInit() {
    this.latitude = this.route.snapshot.params["lat"];
    this.longitude = this.route.snapshot.params["lon"];
    console.log("1- Lat: " + this.latitude + ", Lon: " + this.longitude); //OK!
  }

  //Map events
  onMapReady(event) {
    console.log('Map Ready');   

    this.mapView = event.object;   

    console.log("2- Lat: " + this.latitude + ", Lon: " + this.longitude); //OK!

    //this.mapView.updateCamera(); //NOT working!!!

    this.mapView.latitude=this.latitude;
    this.mapView.longitude=this.latitude;

    console.log("Setting a marker...");

    var marker = new Marker();
    marker.position = Position.positionFromLatLng(this.latitude, this.longitude);
    marker.title = "JLD Saldanha";
    marker.snippet = "Av. Duque D'Avila, n°46C 1050-053 Lisboa";
    marker.userData = { index: 1 };
    this.mapView.addMarker(marker);
    marker.showInfoWindow();   

    
  }`

**Comment by pvcoelho** [comment]
Problem solved:

Issue was that route parameters in angular are strings and the component variables latitude and longitude are numbers so it was not able to properly assign values in OnInit.

Solved problem by converting strings to numbers by adding the + prefix:

`  ngOnInit() {
    this.latitude = +this.route.snapshot.params["lat"];
    this.longitude = +this.route.snapshot.params["lon"];    
  }`
