### ISSUE TITLE
No Resource Found error when attempting to build on android

### ISSUE THREAD

**Issue by fayezm** [dapriett/nativescript-google-maps-sdk#262]
I am receiving the below error when attempting to run on android. I have confirmed that the appropriate keys exist in strings.xml and in nativescript_google_maps_api.xml

AAPT: No resource found that matches the given name (at 'value' with value '@string/nativescript_google_maps_api_key').

This is the version info from tns
✔ Component nativescript has 4.0.0-2018-03-22-11248 version and is up to date.
✔ Component tns-core-modules has 4.0.0-rc-2018.3.12.2 version and is up to date.
✔ Component tns-android has 4.0.0-rc-2018.3.22.1 version and is up to date.
✔ Component tns-ios has 4.0.1-rc-2018-03-22-01 version and is up to date.

I have android api 25 installed
It works fine on iOS

**Comment by dapriett** [comment]
Closed by #268
