### ISSUE TITLE
"Cannot read property 'android' of undefined"

### ISSUE THREAD

**Issue by NextStepToUp** [dapriett/nativescript-google-maps-sdk#27]
Calling js method onCreateView failed
TypeError: "Cannot read property 'android' of undefined"
File: "/data/data/org.nativescript.AppName.files.app.tns_modules/nativescript-google-maps-sdk/map-view.js". line: 32, colomn: 39

**Comment by dapriett** [comment]
Make sure you have the Google Play services SDK install, and try reinstalling...

```
rm -rf node_modules platforms
tns install
```

**Comment by NextStepToUp** [comment]
Thanks. It halped me =)

**Comment by shyandsy** [comment]
@dapriett  how to install the  Google Play services SDK for nativescript??
