### ISSUE TITLE
How to create a compass

### ISSUE THREAD

**Issue by zuohuadong** [dapriett/nativescript-google-maps-sdk#285]
![image](https://user-images.githubusercontent.com/11203929/40730224-b9eabcea-6460-11e8-966e-e6d36ca713ae.png)

I'd like to make a separate compass. But no corresponding interface was found.

**Comment by csi-stasik** [comment]
You need to do it manually, look here https://github.com/NativeScript/NativeScript/issues/5889#issuecomment-507413711
