### ISSUE TITLE
Build error on Android with NS 4.1

### ISSUE THREAD

**Issue by erjdriver** [dapriett/nativescript-google-maps-sdk#287]
NS Core project - using 4.1.

Getting the following error during build

`Unable to apply changes on device: emulator-5554. Error is: Failed to build plugin nativescript-google-maps-sdk : 
Error: Command ./gradlew failed with exit code 1 Error output: 
 
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':releaseCompileClasspath'.
> Could not find common.jar (android.arch.core:common:1.0.0).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/core/common/1.0.0/common-1.0.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
`

I created a new folder structure 

./app/App_Resources/Android/src/main/res/values and added the xml file there with the api key.

In the above, I had the create the src/main/res/values folder - wasn't there before.

I also added the meta entry to AndroidManifest.xml file.

The demo program seems to store the xml file in `Android/src/main/assets` folder - not sure which is correct.

Also getting this error message 

`No manifest found in /Users/asrock/Documents/test/app/App_Resources/Android/src/main/AndroidManifest.xml`

**Comment by erjdriver** [comment]
No...but I did find out that NS 4 or 4.1 and above - the folder structure below Android is different.

so I have app/App_Resources/Android/src/main/res and have all the drawables etc there.

in Android/src/main have AndroidManifest.xml
![temp](https://user-images.githubusercontent.com/1229041/41124805-171ce92c-6a71-11e8-9348-b91668b23dcd.png)

**Comment by CapellaBlue** [comment]
This is how mine is structured as well.  When I followed the install for NativeScript > 4, the `cp` command created the `Android/src/....` file. I moved my AndroidManifest.xml in there. It didn't change the error. -- i just dont see the "couldnt find manifest" error pop up before the "FAILURE"

I thought I could use some react answers to help, and found people adding this to their build.gradle. SO i added it to my Android/app.gradle. No dice. 
```
maven {
  url "https://maven.google.com"
}
```

**Comment by CapellaBlue** [comment]
![screen shot 2018-06-07 at 1 55 38 pm](https://user-images.githubusercontent.com/15096082/41125835-7f2e5a26-6a5a-11e8-8cd7-4aa8eba8ae78.png)
^mine. I have NS 4+. hm.

**Comment by erjdriver** [comment]
I think you need to move all your drawables under res also.

Basically only 2 items under src/main should be AndroidManifest.xml and res folder.

The url it's looking for 

`https://jcenter.bintray.com/android/arch/core/common/1.0.0/common-1.0.0.jar`

Seems to be unavailable when I check using a browser.

So maybe they're doing some maintenance or something.

**Comment by erjdriver** [comment]
The folder /1.0.0 contains a .pom file instead of a .jar file.

Folder /1.1.1 does contain a common-1.1.1.jar file.

I believe a .pom file is a maven makefile...

Hopefully someone in the know will chime in...I'm stumped.

**Comment by CapellaBlue** [comment]
me, too. did you try changing the .pom to .jar?

I tried adding the maven to platform/Android/build.gradle, too-- and I read on SO that doing this updates the play-services versions-- so I tried manually updating those from 11.2.0 to 11.3.0:
project.ext {
  googlePlayServicesVersion = "11.3.0"
}

no dice

**Comment by erjdriver** [comment]
I believe google-play-services version numbers are a single number - right now 49 is the latest.

I've got 46 installed because 49 has other dependencies.

**Comment by CapellaBlue** [comment]
no, it's three. It actually appears they just released 15.0.0

https://developers.google.com/android/guides/releases

**Comment by CapellaBlue** [comment]
When I go here: https://jcenter.bintray.com/ ... looking for  https://jcenter.bintray.com/android/arch/core/common/1.0.0/common-1.0.0.jar... I come up empty handed.

Where can we change the url listed above? I think if we find WHERE the common.jar file is...and change the code that points the plugin to the wrong url listed above...we'll be set. 

or not. Oh, debugging, how I love you.

**Comment by erjdriver** [comment]
In the sdk manager - it says version 46.

Do you know what that equates to in the other version system.

Are you using version 49??

I doubt that'll fix it - but I'll try it.

**Comment by CapellaBlue** [comment]
I just reverted my tns version to 3.4.2....and it works for me now.

**Comment by erjdriver** [comment]
This plugin doesn't seem to be compatible with android@4.1.* - works with android@4.0.*

Of course 4.1.2 critical bug in web view.

I guess back to 3.4.3.

One step forward - two steps back.

**Comment by dlcole** [comment]
For what it's worth, I'm seeing the same error.  I've tried updating all the items in the SDK manager, but no luck.

**Comment by FranciZ** [comment]
Hmm, this plugin works just fine on my other laptop with 4.2.* tns-android, but has this error on another one with a fresh setup. Probably due to some issue with the SDK or Play Services version. Maybe this info helps diagnose.

**Comment by erjdriver** [comment]
@FranciZ did you mean tns-android 4.1.2.

Would you mind posting a screenshot of your android sdk manager -showing the installed modules.

**Comment by FranciZ** [comment]
**tns-android version:**
```
"tns-android": {
      "version": "4.2.0-2018-06-06-01"
    }
```

<img width="671" alt="screen shot 2018-06-09 at 23 45 55" src="https://user-images.githubusercontent.com/2536035/41195977-e3af75c0-6c3f-11e8-8d36-56051b240f69.png">
<img width="640" alt="screen shot 2018-06-09 at 23 45 42" src="https://user-images.githubusercontent.com/2536035/41195978-e3d364b2-6c3f-11e8-84d8-0cf99400de8f.png">

**Comment by erjdriver** [comment]
That 4.2.0 version - is that android@next  or android@rc

I believe 4.1.2 is the latest official release.

**Comment by idoadse** [comment]
Happens also to me.

@FranciZ - I did it, the error still happening on my side...

The weird issue is that on other Mac that configured the same as mine with the same project it doesn't happens.

**Comment by erjdriver** [comment]
I tried android@4.2.0-2018-06-06-01 - same error message.

**Comment by CapellaBlue** [comment]
I've read that if you use maven your play version gets updated. As such, while using 4.1,  I tried several play service versions (I manage this in my app.gradle file)-- Is there a different way to test play services versions?

I hope the thread at least helps some folks.

**Comment by shabib3** [comment]
+1

@dapriett - any ideas here?

**Comment by erjdriver** [comment]
I know it builds on android@4.0.1 and fails with android@4.1.0 - so that should narrow it down - whoever is responsible for tns-android. It doesn't seems to be an issue with this plugin but with tns-android.

I'll take this bug report over there.

**Comment by hackerunet** [comment]
So, how can I fix this? 
```
 tns info
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 4.0.0 and the latest available version is 4.1.0.
⚠ Update available for component tns-core-modules. Your current version is 4.0.0 and the latest available version is 4.1.0.
⚠ Update available for component tns-android. Your current version is 4.0.1 and the latest available version is 4.1.2.
```

**Comment by erjdriver** [comment]
You should not be running into this problem with your version. 

I believe you can install 4.0.1 of NS, TNS-CORE and ANDROID and this plug-in will be built successfully.

I just did it this morning.

**Comment by sserdyuk** [comment]
Same problem here in a brand new Sidekick project on NS 4.1. As soon as I added nativescript-google-maps-sdk plugin, the project stopped building.

**Comment by hackerunet** [comment]
sorry but it's happening, I did a tns update and re ran the script and this is the full output.
```
Successfully prepared plugin tns-core-modules-widgets for android.
Unable to apply changes on device: emulator-5554. Error is: Failed to build plugin nativescript-google-maps-sdk : 
Error: Command ./gradlew failed with exit code 1 Error output: 
 
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':releaseCompileClasspath'.
> Could not find runtime.jar (android.arch.lifecycle:runtime:1.0.0).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/lifecycle/runtime/1.0.0/runtime-1.0.0.jar
> Could not find common.jar (android.arch.core:common:1.0.0).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/core/common/1.0.0/common-1.0.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 17s
.
Executing after-watch hook from /home/hackerunet/Projects/flamingo-ice/hooks/after-watch/nativescript-dev-sass.js
Stopping nativescript-dev-sass watcher

```
Updated the environment already
```
✔ Getting NativeScript components versions information...
✔ Component nativescript has 4.1.0 version and is up to date.
✔ Component tns-core-modules has 4.1.0 version and is up to date.
⚠ Update available for component tns-android. Your current version is 4.0.1 and the latest available version is 4.1.2.
✖ Component tns-ios is not installed.
```

**Comment by erjdriver** [comment]
Please read my earlier comments - it DOES happen with 4.1.0 but doesn't with 4.0.1

**Comment by hackerunet** [comment]
@erjdriver ok, downgrading then... again.

**Comment by erjdriver** [comment]
Looks like NS 4.1 is going to a new folder structure - but it seems to be compatible.

I would recommend 4.0.x only if your app does NOT use webview - 4.1.2 I think fixes a critical bug that's not in 4.0.x.

If your app uses webview - I would downgrade to android@3.4.3.

**Comment by hackerunet** [comment]
Just downgraded to 4.0.1 I'm not using webview at all, and still failed.
```
Successfully prepared plugin tns-core-modules-widgets for android.
Unable to apply changes on device: emulator-5554. Error is: Failed to build plugin nativescript-google-maps-sdk : 
Error: Command ./gradlew failed with exit code 1 Error output: 
 
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':releaseCompileClasspath'.
> Could not find common.jar (android.arch.core:common:1.0.0).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/core/common/1.0.0/common-1.0.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by hackerunet** [comment]
I think the plugin would got obsolete because main dependencies repositories maybe doesn't longer exists or it should be updated, the jcenter.bintray.com common-1.0.0.jar doesn't exist, so maybe we need to map this repository to another resource. how can I achieve that?

**Comment by hackerunet** [comment]
@erjdriver This is the current repository where the missing file is, https://mvnrepository.com/artifact/android.arch.core/common/1.1.0 so how can I update the plugin to look in that place instead of it's current resources?

**Comment by shabib3** [comment]
@hackerunet is right, to get `common-1.0.0.jar` the plugin should no longer point to jcenter

**Comment by jeffswitzer** [comment]
To avoid some possible confusion and possibly help, I'll chime in that I'm not experiencing this issue on an older project after migrating it to 4.1.0, because I don't believe that project was converted to the new directory structure some of you are mentioning.

tns --version 4.1.0
"nativescript-google-maps-sdk": "^2.6.0"

dir structure under app/App_Resources/Android for project that was created before 4.1.0
```
.
├── AndroidManifest.xml
├── app.gradle
├── drawable-hdpi
│   ├── animals.png
│   ├── background.png
│   ├── icon.png
│   └── logo.png
├── drawable-ldpi
│   ├── animals.png
│   ├── background.png
│   ├── icon.png
│   └── logo.png
├── drawable-mdpi
│   ├── animals.png
│   ├── background.png
│   ├── icon.png
│   └── logo.png
├── drawable-nodpi
│   ├── animals.png
│   └── splash_screen.xml
├── drawable-xhdpi
│   ├── animals.png
│   ├── background.png
│   ├── icon.png
│   └── logo.png
├── drawable-xxhdpi
│   ├── animals.png
│   ├── background.png
│   ├── icon.png
│   └── logo.png
├── drawable-xxxhdpi
│   ├── animals.png
│   ├── background.png
│   ├── icon.png
│   └── logo.png
├── values
│   ├── colors.xml
│   ├── nativescript_google_maps_api.xml
│   └── styles.xml
└── values-v21
    ├── colors.xml
    └── styles.xml
```

Then in AndroidManifest.xml I have:

```
<meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="@string/nativescript_google_maps_api_key" />
```

and in nativescript_google_maps_api.xml

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
     <string name="nativescript_google_maps_api_key">mike</string>
</resources>
```

However when I create a new project under 4.1.0 I do see this new directory structure:
```
.
├── app.gradle
└── src
    └── main
        ├── AndroidManifest.xml
        └── res
            ├── drawable-hdpi
            │   ├── background.png
            │   ├── icon.png
            │   └── logo.png
            ├── drawable-ldpi
            │   ├── background.png
            │   ├── icon.png
            │   └── logo.png
            ├── drawable-mdpi
            │   ├── background.png
            │   ├── icon.png
            │   └── logo.png
            ├── drawable-nodpi
            │   └── splash_screen.xml
            ├── drawable-xhdpi
            │   ├── background.png
            │   ├── icon.png
            │   └── logo.png
            ├── drawable-xxhdpi
            │   ├── background.png
            │   ├── icon.png
            │   └── logo.png
            ├── drawable-xxxhdpi
            │   ├── background.png
            │   ├── icon.png
            │   └── logo.png
            ├── values
            │   ├── colors.xml
            │   └── styles.xml
            └── values-v21
                ├── colors.xml
                └── styles.xml
```

Not sure why or when this src/main was introduced.

**Comment by dapriett** [comment]
Hey all - don't believe there is a fix needed for this plugin, but for nativescript-android.  Once this pull request gets released, you should be good to go.

https://github.com/NativeScript/android-runtime/pull/1070

Looks like there is another issue opened in their repo, with a possible workaround: https://github.com/NativeScript/android-runtime/issues/1081

**Comment by dlcole** [comment]
I got my 4.1 system building on Android following @dapriett 's links.  Some things to know: 

 To follow the instructions, NativeScript will need to be installed locally (i.e., without sudo).  See [this post](https://discourse.nativescript.org/t/how-to-revert-to-ns-from-4-1-to-4-0-2-on-mac/6340/2) for more info. 

All you need to do is move the reference to jcenter() in build.gradle (NOT in your local app folder), as per the instructions [here](https://github.com/NativeScript/android-runtime/issues/1081). 

I reset the GooglePlayServices in app.gradle back to what I was using in NS 3.4.x, namely: 

```
// See https://github.com/NativeScript/nativescript-geolocation/issues/108
  project.ext {
    googlePlayServicesVersion = "11.2.+"
  }
```

With these changes, I can now build and run successfully on Android.  Woo hoo!

**Comment by hackerunet** [comment]
ok, I don't have any of my libraries/main functions/languages or any other installed with sudo, in fact in linux envs the installation avoid using sudo, I think I get a warning or something like that, but, anyways nothing is builded using sudo.
Also, I have added project.ext several times and the issue persist.
Also I created my project using NS 4.0.1 when I begun, later on, yesterday I updated my env which does not change my directory structure, I don't have any src/main inside app/App_Resources 
so for now I'm goint to read @dapriett comment to see if I can hit the solution, is awfull that including maps in a mobile application is being this hard, it shouldn't be like this and I don't know why globally all languages has the same issues, they all rush up things to release a new feature or new version but programmers don't make efforts to port all features to the new release, there are always bugs somewhere, When I choosed NS to build my project I'd read implementing maps was very straight forward but it is not and is a shame.

**Comment by hackerunet** [comment]
Updates, this finally worked!!, there are a couple of solutions that can be implemented
1) as @dapriett said before -> https://github.com/NativeScript/android-runtime/issues/1081
2) Wipe out all node_modules, npm cache and platforms, then npm install on application's root directory to install everything again, then add the plugin again and then add the platform again, IT HAS TO BE IN THAT ORDER.
Also the application was able to solve the missing jar but not sure how it did that because the resource: https://jcenter.bintray.com/android/arch/core/common/1.0.0/common-1.0.0.jar
is permanently down, that resource doesn't exist anymore, so there is still something missing around.
I also followed the install instructions for NS < 4 no matter if my application was built on NS 4.0.1
Also my nodejs version is v8.11.2 and NPM 6.0.1
That's it!!

**Comment by erjdriver** [comment]
I can confirm the solution here worked.

[](https://github.com/NativeScript/android-runtime/issues/1081)

Just made the change - removed and reinstalled the latest android.

Thanks.

**Comment by sserdyuk** [comment]
Just upgraded to 4.1.3, removed and readded platform and plugin, and still not building. Is some file hacking still required with 4.1.3?

**Comment by hackerunet** [comment]
You need to be extra carefull, is like a surgery procedure, so, remove node_modules, npm cache clean --force then tns plugin add google-maps-sdk, tns platform add android , check you have android runtime prerequisites like api 24+, and other librearies install in the android sdk and of course google play services.

**Comment by sserdyuk** [comment]
I think patching the global build.gradle file is a working workaround, but I wouldn't call it a solution. I followed up on [android-runtime/issues/1081](https://github.com/NativeScript/android-runtime/issues/1081).

**Comment by LeCoupa** [comment]
This fixed the issue for me:

```
tns platform remove android
tns platform add android
```
