### ISSUE TITLE
using the sdk with angular 2

### ISSUE THREAD

**Issue by denkomanceski** [dapriett/nativescript-google-maps-sdk#29]
Hi, I managed to use the plugin with angular2 but I am not able to add the event listeners on the map tag 
```
(markerSelect)="onMarkerSelect"
(cameraChanged)="onCameraChanged"
```

I added brackets because thats how it should be in angular (I also tried without) but the functions do not seem to be called.

Anyone has any idea?

Thanks

**Comment by dapriett** [comment]
Maybe try `(markerSelect)="onMarkerSelect($event)"` and `(cameraChanged)="onCameraChanged($event)"`

**Comment by denkomanceski** [comment]
I tried like that and it didnt work, than i saw the function was static :( 

now it works.

Thanks

**Comment by FranciZ** [comment]
@denkomanceski Hey, could you share how you managed to get this working. Below is my code that I can't get to work.

```html
<MapView (mapReady)="onMapReady($event)"
                   (markerSelect)="onMarkerEvent($event)"
                    [latitude]="latitude"
                    [longitude]="longitude"
                    [zoom]="zoom"></MapView>
```

**Comment by FranciZ** [comment]
Never mind. My issue with implementation.

**Comment by Julio77** [comment]
Hello, any way to execute something after the marker selection is removed ?, for example, I want to show some controls when the marker is selected, this part I already have, but when I remove the marker selection and click on the map I do not know how to execute code to hide my views.

Thank you!
