### ISSUE TITLE
How to bind data to the map in the code behind?

### ISSUE THREAD

**Issue by kvnphllps** [dapriett/nativescript-google-maps-sdk#3]
Hi @dapriett - Sorry to keep bugging you! I was wondering how one binds data to the map in the xml:

```
<maps:mapView id="theMap" latitude = "{{ latitude }}" longitude = "{{ longitude }} zoom = "{{ zoom }}" mapReady="OnMapReady" /> 

```
from the code behind? I've tried setting the ```bindingContext``` of ```gMap``` with no luck. Any suggestions?

**Comment by dapriett** [comment]
Hi @kvnphllps - you can only bind the camera position of the map at the moment: `latitude`, `latitude`, `zoom`, `bearing`, and `tilt`

In your code https://github.com/kvnphllps/nativescript-map-app/blob/master/app/main-page.js#L6 you can add those to your pageData

```
var pageData = new observableModule.Observable({
     latitude: -33.86,
     longitude: 151.20,
     zoom: 12
});
```

For marker data, you'll need to add each one in javascript as you're doing in `OnMapReady`.  There isn't a way to bind map marker data in the view, although that would be something cool to add in the future.

**Comment by kvnphllps** [comment]
@dapriett, Thanks again!
