### ISSUE TITLE
Unable to find variable GMSServices

### ISSUE THREAD

**Issue by jrthib** [dapriett/nativescript-google-maps-sdk#30]
I've run `tns plugin add nativescript-google-maps-sdk`. When I try to run the conditional to initialize the API key on iOS, the compiler reports that it cannot find the variable GMSServices. Any ideas how to fix it?

**Comment by dapriett** [comment]
You're most likely missing CocoaPods.  See step 2 https://developers.google.com/maps/documentation/ios-sdk/start

**Comment by tpgalan** [comment]
I followed @dapriett 's answer.
I'm able to open .xcworkspace file, use XCode and run the application.
But when I try using Nativescript CLI running

`tns run ios --emulator --watch`

Same message comes again.

Any idea?

**Comment by shyandsy** [comment]
@dapriett 
when I run "pod install", there is error message said

"Could not automatically select an Xcode project, Specify one in your Podfile like so:
    project 'path/to/Project.xcodeproj'"

problem is my project is based on nativescript, and there is no xcode project file like Project.xcodeproj

are there any way or somehow to create that?
