### ISSUE TITLE
IOS build with nativescript angular 2 doesn't work 

### ISSUE THREAD

**Issue by thinkoverit** [dapriett/nativescript-google-maps-sdk#31]
When Nativescript angular2 app with https://github.com/NativeScript/nativescript-angular and  GoogleMaps cocoapods is built and  deployed on IOS simulator an exception is thrown like in below screenshot.

Also can you tell us how we can set Google API key for IOS in main app.ts typescript file, currently if added in app.ts it give compile time error? 

![screen shot 2016-05-25 at 4 28 43 pm](https://cloud.githubusercontent.com/assets/1846646/15538514/51189782-229a-11e6-867e-c117367228bf.png)

**Comment by poorcoder** [comment]
I can not say for the error but. You just simply create a js file on app folder lik app/app.js and put this code...
```
"use strict";
var application = require("application");
if(application.ios) {
  GMSServices.provideAPIKey("PUT_API_KEY_HERE");
}
application.start({ moduleName: "pages/home/home" });
```

**Comment by skdeepak88** [comment]
I dont think we use the above JS file for Angular 2 version of Nativescript. We require/import `nativescript-angular/application` instead of `application`. When I use the above code I get the error Cannot find name 'GMSServices'.

**Comment by dapriett** [comment]
Usually when you can't find `GMSServices`, that means the iOS Google Maps pod didn't get installed.  Make sure you have [cocoapods](https://guides.cocoapods.org/using/getting-started.html#getting-started) installed.

**Comment by thinkoverit** [comment]
Actually this is first error when build is started,  without this line
build succeeds with google map cocoapods installed properly and When app is
run it gives exception too that API key shall be set.

**Comment by skdeepak88** [comment]
I have installed cocoapods. See below:

`gem which cocoapods
/Users/deepak/.gem/ruby/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods.rb`

**Comment by ravindrakw** [comment]
Faced same issue. 
Newbie to Angular and Typescript, so not sure where the issue is but  workaround I am using is export GMSServices in JS module and definition file "d.ts".  My 2 cents that there is a issue in typings.

**Comment by skdeepak88** [comment]
@ravindrakw Can you share the code snippet that worked for you. Just the bits you where talking about above. Thanks :)

**Comment by ravindrakw** [comment]
I have done something like this 

GMSServiceKey.d.ts

`declare function GMSServiceKey(): void;
export = GMSServiceKey;`

GMSServiceKey.js

`module.exports = function () {
        GMSServices.provideAPIKey("YOUR KEY");
};`

in app.component.ts

`import GMSServiceKey = require('./GMSServiceKey');`

and
      
`if (application.ios) {
   GMSServiceKey();
}`

**Comment by leocaseiro** [comment]
I also realised we need to register the Element in PaschalCase `MapView` instead of camelCase `mapView`:

```javascript
registerElement("MapView", () => require("nativescript-google-maps-sdk").MapView);
```

**Comment by dapriett** [comment]
Here's a stackoverflow reference, in case anyone else is having issues:  http://stackoverflow.com/questions/36443476/wiring-up-google-maps-nativescript-plugin-with-angular-2

**Comment by viniciodeltoro** [comment]
I did the steps ravindrakw mentioned and that fixed my issue. Thank you guys

**Comment by dxshindeo** [comment]
Even simpler - in your main.ts file, add 

```
import * as platform from "platform";
declare var GMSServices: any;

// before calling .boostrap
if( platform.isIOS ) {
    GMSServices.provideAPIKey("YOUR KEY");
}
```
