### ISSUE TITLE
Crash on load without any message

### ISSUE THREAD

**Issue by echap** [dapriett/nativescript-google-maps-sdk#32]
Hi,

I'm struggling to make the plugin work on android API 23 on a Mac.

Steps that I've followed :
 install the plugin via tns plugin add
 Adding the nativescript_google_maps_api_key with a freshly generated one
 Removing the android platform
 Building for scratch

Still my app is crashing down directly, without any warning or anything. I don't know how to adress my issue. 

Without the plugin, my app works like a charm.
Thing is that one of my coworker has exactly the same app running on linux, and the app works with its build. (works also with the phone I'm using, and his).

Thanks for your great job !

(Running on {N} angular 2.0.0, both of us)

**Comment by dapriett** [comment]
What's crashing - the android emulator?  I use the [Genymotion ](https://www.genymotion.com/features/) emulator for Mac and haven't had any issues.  You can maybe try looking at the logs from android when it crashes - [Device monitor](http://developer.android.com/tools/help/monitor.html) or [logcat](http://developer.android.com/tools/help/logcat.html).

**Comment by echap** [comment]
I tried with an `adb logcat | grep F` and turns out that this may make things evolving, here's what I do have :
>05-27 08:51:42.868 11496 11496 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source)
05-27 08:51:42.868 11496 11496 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
05-27 08:51:42.872  4634  7012 W ActivityManager:   Force finishing activity org.nativescript.gpadri/com.tns.NativeScriptActivity
05-27 08:51:42.935  4634 10558 I Adreno  : Remote Branch                    : quic/LA.BF64.1.2.9_v2
05-27 08:51:48.304  4634  4710 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
05-27 08:51:49.373 11521 11521 E AndroidRuntime: FATAL EXCEPTION: main
05-27 08:51:49.373 11521 11521 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: Incorrect provider authority in manifest. Most likely due to a missing applicationId variable in application's build.gradle.

I will go deeper with this and tell you if I find what was wrong ! thansk for your reply

**Comment by echap** [comment]
I went through a working solution :

Turns out that, as said in the logs above, **the application Id is missing.**. This issue can be resolved with adding the application id in file `<your_project_directory>/app/App_Resources/Android/app.gradle` .

With our id (_org.nativescript.gpadri_) the file should look like
`
android {


  defaultConfig {  
    generatedDensities = []
    **applicationId "org.nativescript.gpadri"**
  }  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }  
} 
`

This issue can be very tricky, since the project will compile correctly when builded with android, but does not work when builded with a mac.
