### ISSUE TITLE
addTileOverlay and TileOptions

### ISSUE THREAD

**Issue by poorcoder** [dapriett/nativescript-google-maps-sdk#33]
Hi, 

We trying to use custom tile overlay provider with your sdk but we can't find any solution, can you can this feature?

**Comment by dapriett** [comment]
Hello @poorcoder - the plugin doesn't currently support TileProviders out of the box, but you should be able to.

Look at [iOS-SDK tiles](https://developers.google.com/maps/documentation/ios-sdk/tiles) and [Android-SDK tiles](https://developers.google.com/maps/documentation/android-api/tileoverlay)

**Comment by poorcoder** [comment]
Thank you @dapriett 
Thanks for your work...

**Comment by pattrawuth2530** [comment]
Hello @poorcoder @dapriett 
I try to find many way to solve this problem but doesn't work. If you have the solution please share a completely example code.
Thank you.
