### ISSUE TITLE
failed to find module: "nativescript-google-maps-sdk", relative to: app/tns_modules

### ISSUE THREAD

**Issue by vigneshwargupta** [dapriett/nativescript-google-maps-sdk#336]
I am integrating gmap with Nativescript + Typescript.
My solution is building but when check the preview with "tns preview". it always throw error. The error text is long but the problem is 
failed to find module: "nativescript-google-maps-sdk", relative to: app/tns_modules

Please help me i am stuck from last 4 days.

**Comment by strenkml** [comment]
The plugin won't work with the live preview.  You will either have to use an emulator or connect your phone to your computer.

**Comment by vigneshwargupta** [comment]
Thanks Perfect reply. I used emulator and it is working.
