### ISSUE TITLE
Build fails when plugin is added - Android

### ISSUE THREAD

**Issue by markosole** [dapriett/nativescript-google-maps-sdk#353]
Hi all,

I would like to report problems with building app when this plugin is installed.
I have created simple app from template and ONLY installed this plugin. App does not build.

**Version: 1.17.0-v.2019.5.31.1 (latest)
NativeScript CLI version: 5.4.2
CLI extension nativescript-cloud version: 1.17.6
CLI extension nativescript-starter-kits version: 0.3.5

Android version 5.4.0 and Platform API 28. **

**Error log:**

> [19-07-13 03:07:03.357] Error detected during LiveSync on 88XY030EM for C:\Users\...\testnacrash. Error: Command gradlew.bat failed with exit code 1 Error output: 
 C:\Users\...\platforms\android\app\src\main\AndroidManifest.xml:22:18-91 Error:
	Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:8:5-17:19 to override.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
  	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:8:5-17:19 to override.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1s

**This is happening on 2 different apps and can be replicated any time using Sidekick NS template.**

**Comment by anteriovieira** [comment]
Hi @markosole 

try https://github.com/dapriett/nativescript-google-maps-sdk/issues/341

Then do the following:

```bash
$ tns platform clean android
...
$ tns run android --bundle
```

**Comment by markosole** [comment]
WoW!!!! Man this works! :D :D Thanks a lot. Is there any chance that plugin is going to be updated and this problem fixed by supporting latest PlayServices?
