### ISSUE TITLE
Info window: tns-core-modules/ui/utils doesn't have a _layoutRootView method anymore

### ISSUE THREAD

**Issue by logangeorge01** [dapriett/nativescript-google-maps-sdk#354]
In map-view.ios.js the mapViewMarkerInfoContents function calls tns-core-modules/ui/utils ios._layoutRootView which does not exist in tns anymore as of pull request #7382 on June 25. I don't know whether this breaks all info windows or just custom ones, but it's throwing this error and crashing the app.

JavaScript error:
file:///node_modules/nativescript-google-maps-sdk/map-view.js:164:30 JS ERROR TypeError: __webpack_require__("../node_modules/tns-core-modules/ui/utils.js").ios._layoutRootView is not a function. (In '__webpack_require__("../node_modules/tns-core-modules/ui/utils.js").ios._layoutRootView(content, CGRectMake(0, 0, width, height))', '__webpack_require__("../node_modules/tns-core-modules/ui/utils.js").ios._layoutRootView' is undefined)

**Comment by EmielH** [comment]
I'm having the same problem. Looking at [the pull request](https://github.com/NativeScript/NativeScript/pull/7382), this broke from Nativescript 6. Apparently the method was already deprecated, see [here](https://github.com/NativeScript/NativeScript/pull/7382/files#diff-46e238aa78a621ace3b04db54626f818). The commit doesn't mention an alternative, unfortunately.

This basically means it's impossible to use infowindows on iOS when using Nativescript 6.

**Comment by logangeorge01** [comment]
Thanks. We switched to using an infowindow not tied to the map, which works way better anyways because we can actually use data binding since it's an actual component now.

**Comment by EmielH** [comment]
@logangeorge01, could you please reopen this issue? I'm glad to see that you have found an alternative solution, but I (and probably other people as well) would like to keep using the map's infowindows. The bug in this library has not been solved yet. Thanks a lot!

**Comment by dlcole** [comment]
I have the same issue, and agree with @EmielH .  I gather the new approach is not yet available, as the code, demo, and readme have not been changed recently.  What alternatives do we have?

**Comment by logangeorge01** [comment]
We decided to create a custom info window component that we show/hide based on marker tap. It allows for a LOT more customizability than the hacky Google Maps info window.

**Comment by EmielH** [comment]
I'm afraid we may have to go that way as well, as there doesn't seem to be any activity in this repo, and unfortunately I currently don't have the knowledge to fix this bug myself.
