### ISSUE TITLE
Typo - get longitude method.

### ISSUE THREAD

**Issue by vtrend** [dapriett/nativescript-google-maps-sdk#36]
Before anything else, thanks for stepping up and getting this done for the community.

There is a typo in "map-view.ios.js" at line #185

`return this._ios.latitude;` should be `return this._ios.longitude;`

Same issue on "map-view.android.js" at line #250

`return this._android.latitude;` should be `return this._android.longitude;`

**Comment by dapriett** [comment]
Good eye, thanks @vtrend!  I'll push out a fix later today
