### ISSUE TITLE
adding functionality for OnDraggingMarker

### ISSUE THREAD

**Issue by jaimeglez** [dapriett/nativescript-google-maps-sdk#37]
Hi all, 

I just add to my app the OnMarkerDragListener for android, it could be nice to add to your plugin

this is what I did for android

``` 
gMap.setOnMarkerDragListener(new com.google.android.gms.maps.GoogleMap.OnMarkerDragListener({
    onMarkerDrag: function(gmsMarker) {
      return this;
    },
    onMarkerDragEnd: function(gmsMarker) {
      callback(gmsMarker);
      return this;
    },
    onMarkerDragStart: function(gmsMarker) {
      return this;
    }
  }));
```
Now the thing is that I also want to implement this listener to IOS but I could figure out how to do that, I have been read and found how to make the instance of GMSMapViewDelegate:

``` 
  var MyMapViewDelegate = NSObject.extend({
    didEndDraggingMarker: function(map, marker, event) {
      console.log("did drag marker with event");
    }
  }, {
    protocols: [GMSMapViewDelegate]
  });

  var mapViewDelegate = MyMapViewDelegate.alloc().init();
  gMap.delegate = mapViewDelegate;
```

The listener is not working with this code, could you give a hand with this. Also once listener for IOS is working we could add to the list of support events such as `markerSelect ` or `cameraChanged `

**Comment by dapriett** [comment]
Hey @jaimeglez - drag events should be good to go
