### ISSUE TITLE
infoWindow content is not updating

### ISSUE THREAD

**Issue by mannok** [dapriett/nativescript-google-maps-sdk#379]
mapReadyHandler(evt){
			evt.object.infoWindowTemplate = `
				<FlexboxLayout flexDirection="column" style="width: 200; height: 200; background-color: blue;">
					<Label text="{{userData.addr}}" style="flex-shrink: 0; color: red;" />
				</FlexboxLayout>
			`;
		}

Hi, I have the above code. Whenever I click on each marker at the first time. The `userData.addr` shows correctly. However, when I further update the `userData.addr` to other value. The content in the info windows is not updated anymore even though I close and reopen the same info window (by clicking on the marker again).

How can I achieve into window content update? Thanks in advance.

**Comment by dlcole** [comment]
See my similar issue: [https://github.com/dapriett/nativescript-google-maps-sdk/issues/372](https://github.com/dapriett/nativescript-google-maps-sdk/issues/372)

**Comment by mannok** [comment]
@dlcole This is the fastest reply I ever get in github issue.   Thanks   haha
