### ISSUE TITLE
How to contribute ? 

### ISSUE THREAD

**Issue by RignonNoel** [dapriett/nativescript-google-maps-sdk#383]
Hi all!

I've a project based on this plugin and i want to add some events available in it, i already know how to do it and where to find the GoogleMaps documentation but i did not found an official documentation on `nativescript-google-maps-sdk` to know how to contribute.

Is there some tests procedure ? Process ? Way to build correctly the plugin to test in local ?

@dapriett if you have some input i will be happy to help you on this project with my enhancement and the documentation. You did a really big job :+1:

**Comment by dapriett** [comment]
Greetings, @RignonNoel 

Glad to hear you want to contribute!  Sorry for the lack of formal documentation on the process.

To contribute, all you need to do is create a pull request, and as time permits I have been reviewing, merging, and releasing.  

When a new feature has been added, I typically look for the following:

- Feature support added for both [iOS](https://github.com/dapriett/nativescript-google-maps-sdk/blob/master/src/map-view.ios.ts) and [Android](https://github.com/dapriett/nativescript-google-maps-sdk/blob/master/src/map-view.android.ts)
- Example added in [Demo](https://github.com/dapriett/nativescript-google-maps-sdk/tree/master/demo) project
- Documentation added to [Readme](https://github.com/dapriett/nativescript-google-maps-sdk/blob/master/README.md)

Hope that helps, let me know if you have any questions.

**Comment by RignonNoel** [comment]
Thanks a lot for the links, it saved me some times to rampup!

I close this issue since it's clear for the moment. If we manage to merge my PR on IndoorBuilding i will try to write some documentation for future contributor :)

**Comment by fgutteridge** [comment]
Hey @RignonNoel and @dapriett...

Thanks for all the work you guys have put in to this (especially @dapriett, of course)!
I, too, am trying to get started on contributing some to this project (I've already built some geocoding functionality), however am struggling to get the proper environment set up.

This is my first time working on an NS plugin and I don't find the documentation particularly amazing... Still trying to wrap my head around it all. I have forked and cloned the repo on to my local machine, however receive a number of errors when trying to run the demo (Vue) on iOS.

First off, I noticed that the Demo(s) (at least the Vue one) is still running on NS 5.0, so a `tns migrate` is required before anything else. But even after migrating, it seems that the iOS typings aren't recognized (despite being generated)? I get a number of errors as follows, all referring to a missing type from the Google Maps SDK for iOS:

> **ERROR in ..../nativescript-google-maps-sdk/src/map-view.ts TS2304: Cannot find name 'GMSMapView'.**

It seems as though basically every `GMS` type cannot be found. `references.d.ts` exists in .../src, with the correct reference paths included (for both `tns-platform-declarations` and the generated typings for the Google Maps SDK).

It seems like I'm getting something quite wrong here, perhaps missing a step or two entirely. Thanks for any help or advice you may be able to provide!
