### ISSUE TITLE
Get coordinates from tap

### ISSUE THREAD

**Issue by PAT-Development** [dapriett/nativescript-google-maps-sdk#39]
I am trying to add a marker if the user long pressed at the map. In the source code I found the _coordinateTappedEvent_, how can I use it? 
My try with:
```javascript
public onMapReady(args) {
      this.map = args.object;
      this.map.on(MapsModule.MapView.coordinateTappedEvent, (eventData) => {
        console.log(eventData);
      });
}
```
failed. The callback is never called. If it isn't implemented yet, can I get the coordinates from the View-Tap Event? 

Thanks for your help!

**Comment by dapriett** [comment]
Looks like we forgot to implement that - should work now.

**Comment by PAT-Development** [comment]
That's cool, thank you!
