### ISSUE TITLE
Numerous errors when executing 'tns plugin build'; Demo on NS 5.0

### ISSUE THREAD

**Issue by fgutteridge** [dapriett/nativescript-google-maps-sdk#396]
Hey @dapriett...

Thanks for all the work you have put in to this! I am trying to get started on contributing some to this project (I've already built some geocoding functionality), however am struggling to get the proper environment set up.

This is my first time working on an NS plugin and I don't find the documentation particularly amazing... Still trying to wrap my head around it all. I have forked and cloned the repo on to my local machine, however receive a number of errors when trying to run the demo (Vue) on iOS.

First off, I noticed that the Demo(s) (at least the Vue one) is still running on NS 5.0, so a `tns migrate` is required before anything else. But even after migrating, it seems that the iOS typings aren't recognized (despite being generated)? I get a number of errors as follows, all referring to a missing type from the Google Maps SDK for iOS:

> **ERROR in ..../nativescript-google-maps-sdk/src/map-view.ts TS2304: Cannot find name 'GMSMapView'.**

It seems as though basically every `GMS` type cannot be found. `references.d.ts` exists in .../src, with the correct reference paths included (for both `tns-platform-declarations` and the generated typings for the Google Maps SDK).

It seems like I'm getting something quite wrong here, perhaps missing a step or two entirely. Thanks for any help or advice you may be able to provide!

**Comment by RignonNoel** [comment]
@fgutteridge Last time i contribute Dapriett ask me to update only the `demo` and not the `demo-vue` or the `ng-demo` so i guess that they are not actively maintained.

If you try to run the `demo` it should work.

If you want to try your own change on the basecode with the demo you can follow these step that @nickolanack shared to me:

```
cd ../src/
npm run build
npm run plugin.link 
cd ../demo
tns debug android
```

**Comment by fgutteridge** [comment]
Thanks so much for the quick reply, @RignonNoel! Ah, that all makes sense now--perhaps I can update the Vue demo to keep everything up to date.

I will try what you've so kindly suggested and report back. Thanks!

**Comment by fgutteridge** [comment]
Perfect, @RignonNoel! Thanks very much––everything is up and running now. Hopefully I can update the Angular and Vue demo so everything works out-of-the-box. 

Thanks again!

**Comment by RignonNoel** [comment]
@fgutteridge no problem! Good luck for the functionality, I'm looking forward to see it
