### ISSUE TITLE
Got the following error. What should I do?

### ISSUE THREAD

**Issue by fmmsilva** [dapriett/nativescript-google-maps-sdk#40]
* What went wrong:
A problem occurred configuring root project 'teste2'.
> Could not resolve all dependencies for configuration ':_F0F1DebugCompile'.
   > Could not find any matches for com.google.android.gms:play-services-maps:+ as no versions of com.google.android.gms:play-services-maps are available.
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/android/gms/play-services-maps/maven-metadata.xml
         https://jcenter.bintray.com/com/google/android/gms/play-services-maps/

**Comment by dapriett** [comment]
Means you don't have the Google play services SDK installed on your machine - look in the Android SDK manager.

**Comment by fmmsilva** [comment]
It's already installed and I still got the error... :(

![captura de tela 2016-06-11 as 13 02 13](https://cloud.githubusercontent.com/assets/2180350/15986053/c13e8728-2fd4-11e6-878a-d318caebc574.png)

**Comment by fmmsilva** [comment]
Solved the problem above, but the app crashes when it loads.. :(

**Comment by markfarl** [comment]
Same as, have demo build successfully but won't open, Alert message demo has stopped. happens on genymotion emulator and when sent to S5

**Comment by dapriett** [comment]
What errors are you seeing in the Android logs?

**Comment by markfarl** [comment]
I fixed it, a while back, I had to manually change the app name in the manifest as it didnt match or something like that

**Comment by dapriett** [comment]
Great, thanks.

**Comment by fmmsilva** [comment]
How did you solve it?
