### ISSUE TITLE
How to change map type hybrid to satellite ?

### ISSUE THREAD

**Issue by poorcoder** [dapriett/nativescript-google-maps-sdk#42]
How to change map type hybrid to satellite...

**Comment by dapriett** [comment]
You should be able to set the mapType on the gMap objects - see 

https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html#public-methods

and

https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_map_view.html#a033ff1b0534e81b67c1e393b4b827018
