### ISSUE TITLE
Maps won't load on simulator if the app launched without launching gmaps app

### ISSUE THREAD

**Issue by adel12790** [dapriett/nativescript-google-maps-sdk#427]
Hi, 
I have the plugin implemented into my app and it works normally, except in just one case.

If I created an android emulator for the first time and launched the app on it, the maps won't load.

I would have to open the google maps application first and then if I navigate back to my app and opened the page again, it will load.

is this a known issue? if it is, can it be fixed?

**Comment by adel12790** [comment]
Turns out it was something in my implementation. Thanks.

**Comment by liamcharmer** [comment]
@adel12790  curious to know how you implemented this? What NativeScript version etc?
