### ISSUE TITLE
Polygon fillOpacity

### ISSUE THREAD

**Issue by dimitriospafos** [dapriett/nativescript-google-maps-sdk#429]
Hi,

Is there a way to set "fillOpacity" and "strokeOpacity" on a Polygon ? The only supported fields that I see currently are "fillColor", "strokeColor" and "strokeWidth". Is there any workaround for this ? Any help would be appreciated.

<img width="372" alt="Polygon" src="https://user-images.githubusercontent.com/11997837/92834679-4bccf500-f3a8-11ea-9a1c-a808e35e3759.png">

**Comment by nickolanack** [comment]
https://docs.nativescript.org/ns-framework-modules/color

opacity can be defined in the color
ie `const colorARGB = new Color(100, 255, 100, 100);`

**Comment by dimitriospafos** [comment]
Thank you @nickolanack!
