### ISSUE TITLE
Publish .d.ts with npm

### ISSUE THREAD

**Issue by leocaseiro** [dapriett/nativescript-google-maps-sdk#43]
Hi @dapriett, thank you for this amazing plugin.

I was wondering if you could publish the declaration .d.ts combined with the package?

That would be nice for IntelliSense in my IDE.

Thanks.

**Comment by dapriett** [comment]
Hey @leocaseiro - should be good to go now.  Enjoy!

**Comment by leocaseiro** [comment]
thanks for that
