### ISSUE TITLE
Can't support NS7 

### ISSUE THREAD

**Issue by taothai** [dapriett/nativescript-google-maps-sdk#439]
Can't support NS7

**Comment by dapriett** [comment]
Duplicate of #422

**Comment by AgustinV08** [comment]
@dapriett When will the Nativescript 7 PR will be merged #420?

**Comment by MrSnoozles** [comment]
It still needs some more work to be done. As everyone is working on it in their free time there's no guarantee when it can be merged. Sadly :-) But it is on the way.
