### ISSUE TITLE
How to enable Show Location button?

### ISSUE THREAD

**Issue by ickata** [dapriett/nativescript-google-maps-sdk#44]
Hi,

I am wondering how to enable the Location Button on my map (bottom right):
http://imgur.com/R1KFUtJ

BTW ```animateToLocation``` method of the ```gMap``` object throws error when executed:

```
mapView.gMap.animateToLocation();
```

which resulted in app crash.

**Comment by dapriett** [comment]
I believe you enable my location

```
function onMapReady(args) {
    var mapView = args.object;
    var gMap = mapView.gMap;

    if(mapView.android) {
        gMap.setMyLocationEnabled(true);
    }

    if (mapView.ios) {
        gMap.myLocationEnabled(true);
    }
}
```

**Comment by ickata** [comment]
Not exactly. This is how I enable it:

```
    if (mapView.ios) {
        gMap.myLocationEnabled = true;
    }
```

In iOS ```myLocationEnabled``` is a property (Boolean), not a method. 

Also this only shows the blue dot where your location is. What I want is to display the button at the bottom-right corner, which when pressed moves the map camera to your location. I am sure that this is possible with GMaps API since there is another nativescript-googlemaps plugin which does this by default. But your plugin has more rich API :)

**Comment by Stavanger75** [comment]
+1

**Comment by Stavanger75** [comment]
Hi,

I got this code to work on android and ios. Hope it helps.

       mapView = args.object;
        var gMap = mapView.gMap;

        if(mapView.android) {
            uiSettings = gMap.getUiSettings();
            uiSettings.setMyLocationButtonEnabled(true);
            gMap.setMyLocationEnabled(true);
        }

        if (mapView.ios) {
            gMap.myLocationEnabled = true;
            gMap.settings.myLocationButton = true;
        }



Here is a more complete sample. (not tested). Sorry for the bad formating of the code under.

//Plugin from : https://github.com/NathanaelA/nativescript-permissions
`var permissions = require('nativescript-permissions');`
`var locationPermissionEnabled = false;`

`exports.loaded = function (args) {`
`        page = args.object;`
       
	//Application request the location permission
        permissions.requestPermission(android.Manifest.permission.ACCESS_FINE_LOCATION, "I need these permissions because I'm cool")
            .then(function() {
                console.log("Woo Hoo, I have the power!");
                locationPermissionEnabled  = true;
            })
            .catch(function() {
                console.log("Uh oh, no permissions - plan B time!");
            });
`};`


`exports.onMapReady(args){ `
```
        mapView = args.object;
        var gMap = mapView.gMap;
```

	//Check if user has accepted the application to use location. 
	if(locationPermissionEnabled){
        	if(mapView.android) {
         	   uiSettings = gMap.getUiSettings();
         	   uiSettings.setMyLocationButtonEnabled(true);
         	   gMap.setMyLocationEnabled(true);
        	}

        	if(mapView.ios) {
        	    gMap.myLocationEnabled = true;
        	    gMap.settings.myLocationButton = true;
       		}
	}
` }  `

**Comment by ickata** [comment]
I confirm that the example is working on my side.

Thanks, @Stavanger75 !

**Comment by elpin1988** [comment]
How I do add input autocomplete directions to mapview with angular and typescript on nativescript?

**Comment by MrSinaRJ** [comment]
I got the map working like mentioned by @Stavanger75 , BUT something very weird is going on here!

```
ActivityManager: Start proc 25860:org.nativescript.MapTest/u0a298 for activity org.nativescript.MapTest/com.tns.NativeScriptActivity
JS: Woo Hoo, I have the power!
JS: Uh oh, no permissions - plan B time!
```

how is that possible that console.log prints `.then` and `.catch` body!!!!
Am i missing something or something is wrong here?!
