### ISSUE TITLE
How set <Page xmlns:maps="nativescript-google-maps-sdk"> in Nativescript with Angular 2 and TypeScript?

### ISSUE THREAD

**Issue by yevheni** [dapriett/nativescript-google-maps-sdk#45]
All is ok but I can't set xmlns:maps="nativescript-google-maps-sdk" fo <Page> tag and map not displayed. I know what this thing sets in .component.ts, but I don't know how make it. Please, help me.

**Comment by dapriett** [comment]
Look at this for angular: http://stackoverflow.com/questions/36443476/wiring-up-google-maps-nativescript-plugin-with-angular-2

**Comment by dapriett** [comment]
Updated docs
