### ISSUE TITLE
How to ensure the safety of our api keys in our nativescript app

### ISSUE THREAD

**Issue by rsun-thoughtworks** [dapriett/nativescript-google-maps-sdk#453]
The Google Map api key is going to cash money if stolen.

Is there any way we can protect it and still using this package?

**Comment by standevo** [comment]
You can apply some key restrictions on your https://console.cloud.google.com/ for specific app, ip address etc

**Comment by rsun-thoughtworks** [comment]
> You can apply some key restrictions on your https://console.cloud.google.com/ for specific app, ip address etc

Exactly. Thanks.
