### ISSUE TITLE
Do not specify Cocoapodgit repo as a Podfile source

### ISSUE THREAD

**Issue by mdentremont** [dapriett/nativescript-google-maps-sdk#454]
See: https://github.com/dapriett/nativescript-google-maps-sdk/blob/923d4419ec2d366f7a34b78db7efcec11414a5df/src/platforms/ios/Podfile#L1

This line should be removed so that Cocoapod can use its CDN by default. Using the git repo incurs a massive download which is causing GitHub Actions CI to spend over 30 minutes on this one line.

**Comment by jerbob92** [comment]
Can we please get this fixed, also in a 2.9.x version? This is really annoying. 
A fix has already been provided:
https://github.com/dapriett/nativescript-google-maps-sdk/pull/425
