### ISSUE TITLE
infoWindow open without a click event 

### ISSUE THREAD

**Issue by isabeladowsley** [dapriett/nativescript-google-maps-sdk#460]
Hi all!

Is there a way to trigger the `infoWindow` to be opened without a click event on the marker?

I am calling `onMarkerSelect` from inside another function and not clicking on the marker, which is happening as expected. However, the `infoWindow` is not being opened without the click event on the marker.

Thanks

**Comment by dlcole** [comment]
Yes, use the marker's `showInfoWindow()` method.

**Comment by isabeladowsley** [comment]
Thanks!!
