### ISSUE TITLE
Angular Map not drawing Polylines

### ISSUE THREAD

**Issue by juniorschen** [dapriett/nativescript-google-maps-sdk#464]
![image](https://user-images.githubusercontent.com/46031261/113297188-b1df8200-92d0-11eb-89e2-b1300c0284fa.png)
![image](https://user-images.githubusercontent.com/46031261/113297498-11d62880-92d1-11eb-9209-91895f25d5c3.png)
![image](https://user-images.githubusercontent.com/46031261/113297526-18fd3680-92d1-11eb-9507-b8e255a9631e.png)

**Comment by juniorschen** [comment]
Sample: https://github.com/juniorschen/Teste

**Comment by juniorschen** [comment]
@dapriett

**Comment by liamcharmer** [comment]
same applies to me. works on iOS but not android.

**Comment by liamcharmer** [comment]
@juniorschen  any fix?

**Comment by juniorschen** [comment]
@liamcharmer Actually the array needs more than one polyline element, in my example case the array only had 1 point, so it was unable to draw because it did not have the next point

**Comment by juniorschen** [comment]
@liamcharmer 
I don't remember for sure, but in the end everything worked out by drawing this way:
private drawPolyline(start: { latitude: number, longitude: number }, end: { latitude: number, longitude: number }) {
    const currentPolyline = new Polyline();
    currentPolyline.color = new Color('#e34850');
    currentPolyline.visible = true;
    currentPolyline.geodesic = true;
    currentPolyline.width = 8;
    currentPolyline.addPoint(Position.positionFromLatLng(start.latitude, start.longitude));
    currentPolyline.addPoint(Position.positionFromLatLng(end.latitude, end.longitude));
    this.mapView.addPolyline(currentPolyline);
  }

**Comment by juniorschen** [comment]
@liamcharmer Try if this works for you. 
If we look at the code, in this case I will have to add two polylines at once, different from the test example I put here
