### ISSUE TITLE
Blank/White map view on iOS 8.2 and 9.3.2

### ISSUE THREAD

**Issue by ADjenkov** [dapriett/nativescript-google-maps-sdk#47]
Hi, 

I keep getting completely white map view in my project. Tested on iPhone 5S (8.2) and iPhone 6S(9.3.2).__The app works like a charm on Android devices__ - the map is displayed properly.

I'm using:
- {N} 2.1.1 version
- {N} core-modules 2.1.4 version
- Pods version 1.0.1
- **MapReady event is fired properly**

I have Google project with enabled Google Maps SDK for iOS with proper API Key.
No javascript or native exceptions are thrown...just white map view (all other components around it are properly working - buttons, tab view, labels e.g). 

Any suggestions?
Thanks

**Comment by noomieware** [comment]
@ADjenkov Hi. How did you solve the issue? Happening for me also.
