### ISSUE TITLE
How to set a tag in shapes or markers

### ISSUE THREAD

**Issue by luiguild** [dapriett/nativescript-google-maps-sdk#489]
https://developers.google.com/android/reference/com/google/android/gms/maps/model/Polyline#public-void-settag-object-tag

I'm trying to include a tag into a Marker or Polyline but how can I reach the `setTag` method? My plan is to identify the item when the user interact with it (or a group of them) using some type of id's.

I'm already tried to use `polyline.android.setTag('test')` and `polyline.setTag('')` and also `polyline._android.setTag('')`

Any ideas?

**Comment by nickolanack** [comment]
you could just store an id on the nativescript object. ie polyline._id = 'someValue' or something similar, instead of trying to use the native android method setTag - which would not be the same for IOS
