### ISSUE TITLE
Map not showing after upgrading to {N} 1.5.0

### ISSUE THREAD

**Issue by amjd** [dapriett/nativescript-google-maps-sdk#5]
The map isn't showing up in my application since upgrading to {N} 1.5.0. The map view has the Google logo on the bottom left, but it's otherwise blank. I tried removing and re-adding the plugin, but that didn't work either.

The API key is specified in the proper file according to the instructions, so that's definitely not the issue.

**Comment by dapriett** [comment]
Hi @amjd - I just pushed a new version.  The sample `nativescript_google_maps_api.xml` string values in the plugin were overriding the project's, causing Android to get the wrong API key.  I also updated it for Android to use the new gradle support in version 1.5 for google-play-maps dependencies.  So try removing and adding the plugin.

`tns remove nativescript-google-maps-sdk`
`tns add nativescript-google-maps-sdk`

**Comment by amjd** [comment]
Thanks. It's working now. :)
