### ISSUE TITLE
IOS Map Animation 

### ISSUE THREAD

**Issue by poorcoder** [dapriett/nativescript-google-maps-sdk#50]
Hi all,

I need to remove google maps slide animation...
I have been reading on google documentation and Apple but could not find a solution...

how can I remove the slide animation on map...

```
updateCamera() {
        this.ios.animateToCameraPosition(this._createCameraPosition());
    }
```

**Comment by dapriett** [comment]
Try manually updating it

'''
mapView.ios.camera = GMSCameraPosition.cameraWithLatitudeLongitudeZoomBearingViewingAngle(
            this.latitude,
            this.longitude,
            this.zoom,
            this.bearing,
            this.tilt
        ); 
'''

**Comment by poorcoder** [comment]
Thank you @dapriett solved my problem...
Maybe you can add a future like mapView.animate = true; 
if its true map can animate the map if not no animation...
