### ISSUE TITLE
is fitBounds available ?

### ISSUE THREAD

**Issue by vtrend** [dapriett/nativescript-google-maps-sdk#51]
I have been trying to fit multiple markers without any luck.

It seems that fitBounds is available in iOS thru GMSCameraUpdate fitBounds, but I can not make it work, do you have any insight ?

animateWithCameraUpdate crashes the instance as: unrecognized selector sent to instance.

Thanks,

**Comment by poorcoder** [comment]
animateWithCameraUpdate excepts Position class which is has only lat & lng values...

**Comment by vtrend** [comment]
Here is how it's done, all credits to @mobilemindtec; I hope it helps!

https://github.com/mobilemindtec/nativescript-google-maps-sdk
