### ISSUE TITLE
Couldn't launch the app on Ios

### ISSUE THREAD

**Issue by sivaramsi** [dapriett/nativescript-google-maps-sdk#52]
When am trying to deploy for ios i got the this error
///app/tns_modules/nativescript-google-maps-sdk/map-view.js:86:60: JS ERROR ReferenceError: Can't find variable: GMSMapViewDelegate

But works in android.

**Comment by poorcoder** [comment]
Check is the pod file installing ?

**Comment by sivaramsi** [comment]
yeah now thats working ..now it says GMSServices is undefined , Could you please say where i can put this code.
 if(application.ios) {
  GMSServices.provideAPIKey("PUT_API_KEY_HERE");
}

**Comment by sivaramsi** [comment]
I have resolved that , but got stuck with an error, service exited due to signal abort trap 6

**Comment by poorcoder** [comment]
If app terminates check for syntax errors...

**Comment by dapriett** [comment]
Closing - reopen if there are still issues.

**Comment by nipun0505** [comment]
any help on how this issue was resolved ? I am stuck with this one

**Comment by mrwrighty** [comment]
Did you resolve this, I'm getting the same error.
