### ISSUE TITLE
IOS - How to Open Infowindow

### ISSUE THREAD

**Issue by poorcoder** [dapriett/nativescript-google-maps-sdk#55]
Hi All,

How I can open InfoWindow w/o marker and open it default...

**Comment by dapriett** [comment]
Maybe create a marker with 0 alpha, and open it's infowindow;

Then maybe try
```
mapView.ios.selectedMarker = marker.ios;
```

**Comment by poorcoder** [comment]
It helped me to find correct way thank you...
When I try your solution it give me this error/warning at console...
``` Marker set as selectedMarker while not belonging to this map. Ignoring. ```

Then I find this solution at https://developers.google.com/maps/documentation/ios-sdk/start

This works
```
    marker.ios.map = mapView.ios;
    mapView.ios.selectedMarker = marker.ios;
```
