### ISSUE TITLE
Cluster Feature

### ISSUE THREAD

**Issue by Hirbod** [dapriett/nativescript-google-maps-sdk#57]
Do you have any plans to include clustering? There are official ways provided for android and iOS. I would love to see clustering feature here

**Comment by dapriett** [comment]
Hi @Hirbod - would be a great feature.  I currently don't have the time to work on it, but would welcome any pull requests if someone wants to pick it up.

**Comment by dapriett** [comment]
Clustering guides: [Android] (https://developers.google.com/maps/documentation/android-api/utility/marker-clustering)  [iOS] (https://developers.google.com/maps/documentation/ios-sdk/utility/marker-clustering)

**Comment by naderio** [comment]
I have this implemented in android, I'll see what I can do when I have time

in the mean time, check the code in question that covers marker cluster and heatmap


# app.gradle
```gradle
dependencies {
    // ...
    compile 'com.google.maps.android:android-maps-utils:0.4.+'
    // ...
}
```

# map.android.js
```javascript
function setupMarkerCluster(mapView, markers, options) {
  debug('setupMarkerCluster');
  var mClusterManager = new ClusterManager(utils.ad.getApplicationContext(), mapView.gMap);

  // var renderer = new DefaultClusterRenderer(utils.ad.getApplicationContext(), mapView.gMap, mClusterManager);

  // renderer.onBeforeClusterItemRendered = function (item, markerOptions) {

  //   debug('onBeforeClusterItemRendered');

  //   markerOptions.alpha(0.8);
  //   markerOptions.flat(true);
  //   markerOptions.rotation(item.rotation);

  //   var icon = new Image();
  //   icon.imageSource = imageSource.fromResource('ic_marker_taxi');
  //   var androidIcon = com.google.android.gms.maps.model.BitmapDescriptorFactory.fromBitmap(icon.imageSource.android);
  //   markerOptions.icon(androidIcon);

  // };

  // mClusterManager.setRenderer(renderer);

  mapView.gMap.setOnCameraChangeListener(mClusterManager);

  markers.forEach(function (marker) {
    mClusterManager.addItem(new ClusterItem({
      rotation: marker.rotation,
      getPosition: function () {
        return new LatLng(marker.position[0], marker.position[1]);
      }
    }));
  });

  mClusterManager.cluster();
}
exports.setupMarkerCluster = setupMarkerCluster;

function setupHeatmap(mapView, markers, CONFIG) {
  debug('setupHeatmap');

  var list = new java.util.ArrayList();

  markers.forEach(function (marker) {
    list.add(new LatLng(marker.position[0], marker.position[1]));
  });

  if (CONFIG) {

    CONFIG.mProvider.setData(list);
    CONFIG.mOverlay.clearTileCache();

  } else {

    CONFIG = {};

    CONFIG.mProvider = new HeatmapTileProvider.Builder()
      .data(list)
      .build();

    CONFIG.mOverlay = mapView.gMap.addTileOverlay(new TileOverlayOptions().tileProvider(CONFIG.mProvider));

  }

  return CONFIG;
}
exports.setupHeatmap = setupHeatmap;
```

**Comment by naderio** [comment]
supporting marker cluster and other features require adding extra dependencies which is probably not a good idea to include them by default.
I took the liberty to implement this as separate module https://github.com/naderio/nativescript-google-maps-sdk-utils. It works only on Android for now.

**Comment by dapriett** [comment]
Nice work @naderio!  Yeah, makes sense to keep it separate.  I added a link to your module in the readme.

**Comment by dxshindeo** [comment]
Is the commented fragment of "DefaultClusterRenderer" correct? Because it doesn't throw me any error, but it also doesn't show any `console.log` I put in `onBeforeClusterItemRendered` function. So that function isn't called?

**Comment by dxshindeo** [comment]
The cluster won't even initialize if I don't uncomment the commented part...
