### ISSUE TITLE
Conflicts with firebase

### ISSUE THREAD

**Issue by el-davo** [dapriett/nativescript-google-maps-sdk#58]
Hi. I have been using the maps plugin and it works great. However we now have a requirement to use firebase. This plugin seems to be conflicting with firebase with the error below

Execution failed for task ':processF0F1F2F3DebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/andr
oid-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0.

The firebase plugin we used is here - https://github.com/EddyVerbruggen/nativescript-plugin-firebase

Any help appreciated

**Comment by dapriett** [comment]
You can look at this: https://github.com/dapriett/nativescript-google-maps-sdk/issues/34 and this https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/86

The plugin is setup to use the latest version of Google play services available.  Could be you have a later version installed then what the firebase plugin requires (looks like version 9.2.0).

**Comment by ipsquare** [comment]
I'm having same problem too. 

How to reproduce the problem:

1. tns create app; cd app
2. tns plugin install nativescript-plugin-firebase
3. npm install nativescript-google-maps-sdk --save
4. tns build android

produces conflict :(

Please help.

**Comment by el-davo** [comment]
@dapriett  That fix seems to be  suggesting that i go into the node_modules folder and update each module manually? I definitely cant do that as anyone who checks out the project would have to do the same

**Comment by dapriett** [comment]
I added the ability now to set the SDK version - see commit [9a92655](https://github.com/dapriett/nativescript-google-maps-sdk/commit/9a92655e8b33c51f575f24e7103919bea1c7c794).

Hopefully that solve your issues.  If so, maybe you can ask the other plugins that depend on Google Play Services to reference the same property.

**Comment by el-davo** [comment]
Many thanks, This has fixed my issue
