### ISSUE TITLE
IOS - How to InfoWindow Tap Event

### ISSUE THREAD

**Issue by poorcoder** [dapriett/nativescript-google-maps-sdk#59]
How can I capture InfoWindow tap event ?

**Comment by poorcoder** [comment]
Hi @dapriett ,
I made some changes on files and I made it but is it right way to do it or not... I am not sure...

""My changes""
map-view-common.js
after notifyMarkerTapped function added notifyMarkerInfowindowTapped function...
```
    // infowindow
    MapView.prototype.notifyMarkerInfowindowTapped = function (marker) {
        var args = { 
            eventName: MapView.markerInfowindowTapEvent,
            object: marker 
        };
        console.log('notifyMarkerInfowindowTapped...')
        this.notify(args);
    };
```
and after 
``` MapView.markerSelectEvent = "markerSelect"; ```
I added 
``` MapView.markerInfowindowTapEvent = "infowindowTap"; ```

and after added to map-view.ios.js
```
// after mapViewDidTapMarker function
    // infowindow
    MapViewDelegateImpl.prototype.mapViewDidTapInfoWindowOfMarker = function (mapView, gmsMarker) {
        var owner = this._owner.get();
        if (owner) {
            var marker = owner.findMarker(function (marker) { return marker.ios == gmsMarker; });
            owner.notifyMarkerInfowindowTapped(marker);
        }
    };
```

**Comment by dapriett** [comment]
Looks good to me - then in android you can [setOnInfoWindowClickListener](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html#setOnInfoWindowClickListener%28com.google.android.gms.maps.GoogleMap.OnInfoWindowClickListener%29) with a [OnInfoWindowClickListener](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnInfoWindowClickListener) - similar to how we do it for gMap.setOnMarkerClickListener

You can do a pull request and make the changes, I can merge them in.

**Comment by poorcoder** [comment]
Ok I will try to solve android version too and then will make a pull request...
Thank you...
