### ISSUE TITLE
Error building project with google maps plugin

### ISSUE THREAD

**Issue by rodenp** [dapriett/nativescript-google-maps-sdk#6]
Hi,

I successfully built a sample app with a previous version of your plugin, however with the new version of the plugin i get build errors as shown below. I see now you have removed the dependancy on the old nativescript-plugin-google-play-services plugin.

A problem occurred configuring root project 'games'.
> Could not resolve all dependencies for configuration ':_nativescript-google-maps-sdkDebugCompile'.
   > Could not find any matches for com.google.android.gms:play-services-maps:+ as no versions of com.google.android.gms:play-services-maps are available.
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/android/gms/play-services-maps/maven-metadata.xml
         https://jcenter.bintray.com/com/google/android/gms/play-services-maps/
         file:/Users/osx/Development/nativescript/gmaps/platforms/android/libs/aar/
         file:/Volumes/UserData/usr/local/opt/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-maps/maven-metadata.xml
         file:/Volumes/UserData/usr/local/opt/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-maps/
     Required by:
         :gmaps:unspecified

I do have google play installed at the following location:
/Volumes/UserData/usr/local/opt/android-sdk/extras/google/google_play_services/libproject/google-play-services_lib/libs/

I am new to android and gradle builds. I thought that since you had the dependency in your include.grade file that the gradle build would take care of including the google map dependency. 

I know previous to the gradle integration that you had to use a library add to add the google play jar file. Am i missing something here? 

dependencies {
	compile 'com.google.android.gms:play-services-maps:+’
}

Also did you have any plans on adding the my location option to your plugin? 

Many thanks for a great plugin.

Peter

**Comment by dapriett** [comment]
Looks like gradle can't find the play-services-maps Android library, which needs to be installed on your machine.  Verify that you have the latest Google Play Services installed https://developer.android.com/sdk/installing/adding-packages.html

**Comment by dapriett** [comment]
For my location, you should be able to do something like this, although I haven't tested it:

```
function onMapReady(args) {
    var mapView = args.object;
    var gMap = mapView.gMap;

    console.log("Setting a marker...");

    if(mapView.android) {
        gMap.setMyLocationEnabled(true);
    }

    if (mapView.ios) {
        gMap.myLocationEnabled(true);
    }
}
```

**Comment by rodenp** [comment]
I had google play installed and after i added the google repository my project built successfully.
Also the my location button appeared on android after adding your code suggestion. I did have to add an extra permission to the android manifest:

 <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>

Although everything builds ok and I can see the location button, there is no map shown.
Do you have any suggestions on why this might be?
I'm pretty sure the API key is correct as I have used it before.
It's difficult to debug since 1.5.1 no longer outputs the android logcat as default.

**Comment by rodenp** [comment]
It now works perfectly.
Many thanks for your help with this.
My last issue as to do with incorrect credentials to the API.

**Comment by dapriett** [comment]
Great - glad to hear it's working now.  Enjoy!
