### ISSUE TITLE
Build process for fork

### ISSUE THREAD

**Issue by christocracy** [dapriett/nativescript-google-maps-sdk#60]
Hi, I want to add a longpress event-handler and issue you a PR but I'm new to typescript.

What's your process for building the lib?

I'm using 
```
$ tsc -p tsconfig.json
```

and it fails miserably :)

**Comment by dapriett** [comment]
You can pull in the latest, I removed the `noEmitOnError` setting.  For some reason it throws errors in the typescript classes in npm_modules, even though it's set to ignore them.

**Comment by christocracy** [comment]
So the only thing you do when you're going to publish is as I posted above?

**Comment by dapriett** [comment]
Yep, that's it.  I'm using Intellij so the built in typescript plugin does it for me automatically, but that's the correct command.

**Comment by christocracy** [comment]
Thanks, I thought I tried this.  Works now.  PR for `longclick` event coming soon.
