### ISSUE TITLE
show snippet/title programmatically

### ISSUE THREAD

**Issue by terhoraj** [dapriett/nativescript-google-maps-sdk#63]
Can you add possibility to activate snippet programmatically?

Something like this: http://stackoverflow.com/questions/15899619/opening-infowindow-automatically-when-adding-marker-google-maps-v2-android

**Comment by dapriett** [comment]
It's not exposed directly in the library now, but you should be able to do something like `marker.android..showInfoWindow()` for android.  

For iOs you'll probably have to do something different: http://stackoverflow.com/questions/23820740/how-to-show-all-info-window-in-ios-google-maps-without-tapping-on-marker

`mapView.ios.selectedMarker = marker.ios`

**Comment by dapriett** [comment]
I'll keep it open for a later enhancement or PR.
