### ISSUE TITLE
Cordova-plugin-whitelist

### ISSUE THREAD

**Issue by kekelzpekel** [dapriett/nativescript-google-maps-sdk#65]
Hi, after enabling your plugin my console is getting spammed by:
`chromium: [INFO:CONSOLE(25)] "No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.", source: file:///android_asset/www/plugins/cordova-plugin-whitelist/whitelist.js (25)
`
Can you advice how to fix this or get rid of this message ?

**Comment by christocracy** [comment]
This is a NativeScript plugin -- Not a Cordova plugin.  You're not at the correct repo.

**Comment by kekelzpekel** [comment]
I am aware of that - This started happening after enabling this repo's plugin. I'm guessing nativescript-google-maps-sdk is using webview and that's why I am getting this.

**Comment by christocracy** [comment]
I don't get it.  Are you making a Cordova app or a NativeScript app?

**Comment by kekelzpekel** [comment]
I am making NativeScript 2.2 app with Angular2. Ever since I included this plugin, the message appeared. There is no cordova anywhere in my project.

**Comment by christocracy** [comment]
There is no Cordova anywhere in this project.

I'm well aware what Cordova whitelist is.  I fail to see how it could have anything to with this project.

I'm am not affiliated with this project and I'm relatively new to NS.  I'm an expert with Cordova though.

**Comment by kekelzpekel** [comment]
I re-initiated the project copied over source files and it now works fine, I must have messed something up with some weird dependency. Sorry to have wasted your time
