### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by thiagoterleski** [dapriett/nativescript-google-maps-sdk#69]
Hi, 
there are plans for clustering? This feature is very important! :-)

**Comment by dapriett** [comment]
There is a feature request out there for it #57 - @naderio mentioned he may work it.  If not, I'll welcome PRs!

**Comment by dapriett** [comment]
Duplicate of #57

**Comment by naderio** [comment]
https://github.com/naderio/nativescript-google-maps-sdk-utils
