### ISSUE TITLE
creating InfoWindow

### ISSUE THREAD

**Issue by Nopileos2** [dapriett/nativescript-google-maps-sdk#71]
Hello,

i use this plugin for my app and so far it works very good.
But now i wanted to add InfoWindows and don't find a way how i can do it.

Edit: I guess it is not possible right now, so i just created this #72 so i can handle a Tap on the screen and
redirect me on a Info page.

but some way to create an InfoWindow would be more ideal.

**Comment by dapriett** [comment]
Closed by #72
