### ISSUE TITLE
Sandbox-exec

### ISSUE THREAD

**Issue by eppisapia** [dapriett/nativescript-google-maps-sdk#74]
Hello,

After installing and configuring this library on a project when I try to run find the next issue:

'Processing node_modules failed. Error: Command sandbox-pod failed with exit code 71 Error output: 
 sandbox-exec: /Users/synergyqa/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/bin/pod: Operation not permitted'

What I tried to solve this is:

- Change sandbox's permission (Same issue)
- I read about change Ruby version to 2.1.1 or bellow but Cocoapods require 2.2.2 or further

How can I solve this?

**Comment by poorcoder** [comment]
Did you try this http://stackoverflow.com/a/567105

**Comment by eppisapia** [comment]
Yes, doesn't work

**Comment by eppisapia** [comment]
If another have this error just disable the sand-box at the config file in your NativeScript Folder
