### ISSUE TITLE
mapReady event is never getting called - Angular

### ISSUE THREAD

**Issue by getmetorajesh** [dapriett/nativescript-google-maps-sdk#75]
When using with Angular2 and following the example on Readme, the onMapReady event is never getting called though the map shows up on the ios simulator

**Comment by SittingFox** [comment]
Hmm, I seem to have it working. Even just copy&pasting the example as a whole over what I had seems to work just fine.

Might be something sneaky in there causing the issue, maybe?

**Comment by getmetorajesh** [comment]
thanks for the trying it out @SittingFox. I tried it again on clean slate, and no luck. I have this project [here](https://github.com/getmetorajesh/test_ns_maps). Are you using the latest version of Nativescript 1.8.10 and  nativescript-google-maps-sdk v1.3.11?

**Comment by dapriett** [comment]
Tried out your demo - `mapReady` event fired in Android but not iOS.  In iOS the map is ready immediately, whereas in Android you have to wait for the `OnMapReadyCallback` callback.  It looks like in iOS it fires the event before the component in angular has a chance to register.  Not sure if thats a bug with nativescript-angular, but I added a timeout - should be good now.

**Comment by dimitriospafos** [comment]
Still same issue on nativescript-google-maps-sdk 2.4.2 in ios?
