### ISSUE TITLE
iOS marker and shape visibility

### ISSUE THREAD

**Issue by SittingFox** [dapriett/nativescript-google-maps-sdk#76]
Hi,

It seems there's an issue with making things invisible in iOS. In my emulator, with running the demo, setting all the markers and shapes to be `item.visible = false` doesn't affect them at all. They're always visible.

Running the same code on my Android device works as expected.

**Comment by dapriett** [comment]
Actually, from what I can tell in the iOS SDK, I don't think visibility is supported.  Your best bet to show and hide them is to use the `alpha` property for markers.  For shapes, you can set the `alpha` on the `color`.

**Comment by SittingFox** [comment]
Hmm, OK. So either adjust the alpha or actually remove it then. Alright, thanks! 😄
