### ISSUE TITLE
Custom InfoWindow

### ISSUE THREAD

**Issue by ViVer-7** [dapriett/nativescript-google-maps-sdk#77]
Is there a posibillity to show a custom InfoWindow when a Marker has been clicked?
By using 'snippet' you can only set plaintext, which is limiting my app... :(

When a Marker is clicked, I would like to show an InfoWindow with an image, small piece of text and perhaps a button. Can anyone point me in the right direction?

**Comment by eppisapia** [comment]
Hello @ViVer-7 

You want that the InfoView be showed at same page or Navigate to a 'Marker Detail' page?

I have this code that add information to a Mark and when you tap it, I navigate to a Detail Page sending the information.

Im using TypeScript here but should be similar on Javascript

In my Map page I have an Array "Mark" that contain all the mark's info 

`
let vm = new Observable({ 
    marks:([
        { 
            latitude: 10.498086655450642,
            longitude: -66.85348734185897,
            title: "Caracas",
            snip: "Venezuela",
            location: "My location"
            },

<.... Other code here ....>

OnMapReady(args) {
    var mapView = args.object;
    console.log("Setting a marker...");
    let marcas=vm.get("marks");
    for (let i=0; i<marcas.length; i++){
        var marker = new mapsModule.Marker();
        marker.position = mapsModule.Position.positionFromLatLng(marcas[i].latitude, marcas[i].longitude);
        marker.userData = { index : i+1};
        marker.data=marcas[i];
        mapView.addMarker(marker);
    }
  }
`

As you can see I'm setting in the tribute 'data' all the info of the array position 'marker.data=marcas[i];' so i can access to it like marker.data.location. 

You can do it this way to not overtyping code or if it's specific mark you can also put your own attributes like 'marker.image' 'marker.smalltext' .... 

With this the marker will have info on it so when you tap can use those as arguments 

Hope this help you

Regards

**Comment by ViVer-7** [comment]
I would like the InfoWindow like it is intended, so on The same page. Just like it is now...Just with custom content in stead of plain text.

In your example you pass data, I understand that. But my problem is showing data (which is not Just plain text) inside the InfoWindow...

**Comment by eppisapia** [comment]
I haven't success with function that return element on a position. So I play with AbsoluteLayout and made this:

XML
`
<AbsoluteLayout height="{{height}}" width="{{width}}" >
          <maps:mapView latitude="{{latitude}}" longitude="{{longitude}}" 
          zoom="7" bearing="{{ bearing }}" 
          tilt="{{ tilt }}" mapReady="OnMapReady"  
          markerSelect="onMarkerSelect" 
          height="{{height}}" width="{{width}}" />
          <StackLayout top="0" left="0" id="InfoView" height="{{active == 0 ? '0' : 300}}">
               <Label text="{{Marker_Selected_Name}}"/>
               <image src="{{Marker_Selected_img}}"/>
               <Label text="Close" tap="CloseInfoView" class="Button">
          </StackLayout>
</AbsoluteLayout>
` 
TypeScript
`
onMarkerSelect(args) {
 // Get the path of the Img
    let img=args.marker.img; 
 // Get the name of the marker
    let name=args.marker.name
    vm.set("active", 1);
    vm.set("Marker_Selected_img", img);
    vm.set("Marker_Selected_Name", name);
  }
 CloseInfoView () {
 vm.set("active", 0);
}

`
I'm playing with the Height of the component to show it in the AbsoluteLayout. So when I click a mark the InfoView is "opened" and show the Marker's Name and the Image.
If you need to implement other code in the page just put at Last the component that will overlay other way it will be as background.

**Comment by dapriett** [comment]
Currently the plugin doesn't support it directly - would welcome any pull requests if someone figures it.

For Android looks like you have to setup a custom InfoWindowAdapter

https://developers.google.com/maps/documentation/android-api/infowindows#custom_info_windows
https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.InfoWindowAdapter

You can add something like this here: 
https://github.com/dapriett/nativescript-google-maps-sdk/blob/master/map-view.android.ts#L204
```
   gMap.setInfoWindowAdapter(new com.google.android.gms.maps.GoogleMap.InfoWindowAdapter() {

        getInfoWindow : function(gmsMarker) {
            // return android View
        }

        getInfoContents : function(gmsMarker) {
            // return android View
        }
    });
```

For ios looks like you need to create `markerInfoWindow` and `markerInfoContents` on the `GMSMapViewDelegate` (https://github.com/dapriett/nativescript-google-maps-sdk/blob/master/map-view.ios.ts#L7)

https://developers.google.com/maps/documentation/ios-sdk/reference/protocol_g_m_s_map_view_delegate-p#ab83c3dab588f06e6227794740782bf55

```
class MapViewDelegateImpl extends NSObject implements GMSMapViewDelegate {
...

    public mapViewMarkerInfoWindow(mapView: GMSMapView, gmsMarker: GMSMarker): UIView {
        let owner = this._owner.get();
        if (owner) {
            let marker: Marker = owner.findMarker((marker: Marker) => marker.ios == gmsMarker);
        }

       // return UIView or null
    }

   public mapViewMarkerInfoContents(mapView: GMSMapView, gmsMarker: GMSMarker): UIView {
        let owner = this._owner.get();
        if (owner) {
            let marker: Marker = owner.findMarker((marker: Marker) => marker.ios == gmsMarker);
        }

       // return UIView or null
    }
...
}

```

**Comment by ViVer-7** [comment]
I just tried eppisapia's workaround, but it doesn't seem to work. Problem occurs when the custom 'InfoWindow' is shown. Everything is ok so far, but when I drag the map....the InfoWindow stays at its absolute position...and that's not where the marker is going...

**Comment by dapriett** [comment]
I looked at it real quick to see if I could add custom info window support (see branch: https://github.com/dapriett/nativescript-google-maps-sdk/tree/custom_info_window)

I have a infoWindowTemplate property which you can set like so:

https://github.com/dapriett/nativescript-google-maps-sdk/blob/custom_info_window/demo/app/main-page.js#L91

This seems to work alright in Android, but had no luck in iOS.  If anyone wants to take a look, these are the points of interest:

map-view-common:[_getMarkerInfoWindowContent](https://github.com/dapriett/nativescript-google-maps-sdk/blob/custom_info_window/map-view-common.ts#L93)
map-view.android:[InfoWindowAdapter. getInfoContents](https://github.com/dapriett/nativescript-google-maps-sdk/blob/custom_info_window/map-view.android.ts#L331)
map-view.ios:[MapViewDelegateImpl.mapViewMarkerInfoContents](https://github.com/dapriett/nativescript-google-maps-sdk/blob/custom_info_window/map-view.ios.ts#L130)

**Comment by OhMyLob** [comment]
Still no luck for iOS? 😞

**Comment by dapriett** [comment]
No luck - I have an issue posted to the nativescript team https://github.com/NativeScript/NativeScript/issues/3127

**Comment by Yamilquery** [comment]
I hope soon to achieve some result in IOS... 🐇

**Comment by Dangradz** [comment]
@dapriett I have a problem with infoWindow on Android
this is my code 
`var marker = new mapsModule.Marker();
    marker.icon='foodmarker';
    marker.userData={type: 'post:'+res.key};
    marker.position = mapsModule.Position.positionFromLatLng(res.value.lat,res.value.lng);
     marker.infoWindowTemplate = '~/views/home/prova';
    map.addMarker(marker);
   
    marker.showInfoWindow();`

If I click on the marker, nothing happens

**Comment by edoardocavazza** [comment]
It seems that ios native view does not calculate frame size until placed into another view. In this case, the {N} view instance does not get any parent. I workarounded directly using `require("ui/utils").ios._layoutRootView(content, CGRectMake(0, 0, width, height))` before returning the `content.ios` to the map view delegate and.... it worked! 🎉🎉🎉

**Comment by dapriett** [comment]
Nice 👍 

I added that to the branch, and merged in the latest from Master.  Still seems to have issues with images, which you can see in the demo.  I'm guessing before the view is added before the image has had enough time to load.  On iOS, if you close and reopen infoWindow it shows, on Android it never shows.

**Comment by edoardocavazza** [comment]
not tried with images 🤔 I'll take a look.

**Comment by ErikGrijzen** [comment]
I'm very interested in this feature. What's the current status of the implementation?

**Comment by 3rror404** [comment]
Hi @dapriett,

did this feature make it in to master?

**Comment by Buuhuu** [comment]
This works well with nativescript-angular, though I didn't use images ...

Anyway. One thing missing is, that the _infoWindowView is not unloaded in case a marker is removed from the map. In our nativescript-angular case we would like to get `onUnloaded` called so we can destroy the `ViewRef`.

**Comment by icreatesolutions** [comment]
Is it currently possible to have a custom infowindow?  I updated the current version with the demos and can't seem to find a way.

**Comment by dapriett** [comment]
Sorry for the delay - I merged in the custom info windows feature and updated README.
