### ISSUE TITLE
Android using Nativescript 2.3.0

### ISSUE THREAD

**Issue by DomGaud** [dapriett/nativescript-google-maps-sdk#79]
After upgrading to Nativescript 2.3.0 I receive the following error on Android when loading Google Maps:
`TypeError: com.google.android.gms.maps.GoogleMap.OnCircleClickListener is not a function`

All works If I comment out the following in map-view.android.js
```Javascript
gMap.setOnCircleClickListener(new com.google.android.gms.maps.GoogleMap.OnCircleClickListener({
                    onCircleClick: function (gmsCircle) {
                        var shape = owner.findShape(function (shape) { return shape.android.getId() === gmsCircle.getId(); });
                        if (shape) {
                            owner.notifyShapeTapped(shape);
                        }
                        return false;
                    }
                }));
```

**Comment by dapriett** [comment]
Nativescript 2.3.0 should work fine.  I'm guessing it's an issue with your android google maps sdk - make sure it's installed and you have the latest.

**Comment by dapriett** [comment]
Closing - reopen if you're still having issues.

**Comment by DomGaud** [comment]
Thanks, I'll troubleshoot my Android platform

**Comment by jonathan-casarrubias** [comment]
Im having this issue,

I have the following versions

Nativescript 2.3.0
Android SDK API 24
Build Tools 24
nativescript-google-maps-sdk 1.4.3

I removed the platform directory also the node_modules, but whatever I do I keep getting this error
