### ISSUE TITLE
Marker icon does not work

### ISSUE THREAD

**Issue by abs-abs** [dapriett/nativescript-google-maps-sdk#84]
@dapriett 
Cannot read property 'android' of null is what I see in errors while I use icon property!
The strange problem is that I have not any file named `map-view.android.ts` in my module directory yet there is only `map-view.android.js`!!
I used this `tns plugin add nativescript-google-maps-sdk` but really different with codes in github.
I also removed plugin and re-add but made no difference.
This is my code.
```javascript
        var mapView = args.object;
		var marker = new mapsModule.Marker();
		marker.position = mapsModule.Position.positionFromLatLng(-34, 24); // is fake
		marker.title = "Test";
		marker.snippet = "Test";
		marker.userData = { index : 1};
		marker.icon = "FULL_HTTP_URL"; //does not work even with res:// etc.
		mapView.addMarker(marker);
```

**Comment by dapriett** [comment]
Only the generated JS files gets published to NPM, the TS files are ignored - so that's why it's not in your modules.

The icon fields currently only resource icons without the `res://` in front - so if you have a resource names `icon`, then just `marker.icon = "icon"`;

Now if you need to add an icon from a http url, you could do something like this:

```
// var imageSource = require("image-source");


imageSource.fromUrl("https://www.google.com/images/errors/logo_sm_2.png")
.then(function (image) {
    var mapView = args.object;
        var marker = new mapsModule.Marker();
        marker.position = mapsModule.Position.positionFromLatLng(-34, 24); // is fake
        marker.title = "Test";
        marker.snippet = "Test";
        marker.userData = { index : 1};
        marker.icon = image
        mapView.addMarker(marker);
}, function (error) {
        console.log("Error loading image: " + error);
});

```

**Comment by abs-abs** [comment]
@dapriett  thanks man.
