### ISSUE TITLE
geolocation and direction code snippet

### ISSUE THREAD

**Issue by dhemitus** [dapriett/nativescript-google-maps-sdk#85]
hi,
is there any code snippet for geolocation and direction?

thx

**Comment by nickcoury** [comment]
There isn't currently.

For Geolocation I would look at and use this plugin, the Google Maps SDK won't handle geolocation directly:
https://github.com/NativeScript/nativescript-geolocation
https://github.com/NativeScript/nativescript-geolocation-demo

For directions, if you want to use it in Google Maps you could use Nativescript to access it through each native library directly (or contribute the code to do so back to this plugin!).  If you just want simple directions, look at this plugin:
https://github.com/EddyVerbruggen/nativescript-directions
