### ISSUE TITLE
Extremely high memory and CPU usage on iOS when creating polyline

### ISSUE THREAD

**Issue by 3rror404** [dapriett/nativescript-google-maps-sdk#88]
When creating a polyline with many points on iOS (I'm testing with 5000-10000 points) CPU usage maxes out at ~100% and memory usage increases dramatically  until the app crashes.

```
for(var i=0;i<points.length;i++) {
    var position = mapsModule.Position.positionFromLatLng(points[i].Latitude, points[i].Longitude);
    polyline.addPoint(position);
}

mapView.addPolyline(polyline);
```

The exact same data is processed and render on Android in a couple of seconds without problem.

Example data:

```
[{
    "JourneyEventID": 652883,
    "JourneyID": 3962,
    "Latitude": 52.538412,
    "Longitude": - 1.728048,
    "CreatedDate": "2016-10-19T18:59:11.65"
}, {
    "JourneyEventID": 652884,
    "JourneyID": 3962,
    "Latitude": 52.538467,
    "Longitude": - 1.728063,
    "CreatedDate": "2016-10-19T18:59:11.653"
} {
... x 5000
}]
```

I know this is a lot of data but the difference in performance between platforms is vast.

**Comment by dapriett** [comment]
We probably need to add a bulk add method.  See if this improves it at all

```
for(var i=0;i<points.length;i++) {
    var position = mapsModule.Position.positionFromLatLng(points[i].Latitude, points[i].Longitude);
    polyline._points.push(position);
}
(polyline.android) ? polyline.reloadPoints() : polyline.loadPoints();

mapView.addPolyline(polyline);
```

**Comment by 3rror404** [comment]
Thanks @dapriett
That made an incredible difference. Using ~10000 points, the polyline loads almost instantaneously on iPhone 6 with very limit resource usage.

**Comment by dapriett** [comment]
You can now do `polyline.addPoints(points);`

**Comment by jlafitte** [comment]
I have a very large amount of lines with a large amount of points.  It loads pretty fast on iOS but unusably slow on android.  Do you think it's somehow related to this?

**Comment by ChristofferSkog21st** [comment]
Not sure if related but I've noticed that polygons in general slows down Android a lot. Any idea why that could be?

**Comment by jlafitte** [comment]
I never worked it out, just ended up making native calls with google-maps-utils library and using a polyline layer.  Load about 10x faster.  Think something is wrong here, but doesn't seem like a high priority.
