### ISSUE TITLE
add feature to allow to style the map

### ISSUE THREAD

**Issue by tviel** [dapriett/nativescript-google-maps-sdk#89]
I successfully integrated a google map at my angular2+nativescript project. Everything I needed from the typescript definition file is working for me.

However, I wanted to play around with the styling of the map. AFAIK, today I have to use native calls to the map, as the method setMapStyle() is not in the typescript definition.

I thought I could use the gMap property to access the native object and call the method. But I fail in setting up the right parameter as requested in google docs (https://developers.google.com/maps/documentation/android-api/styling) as I dont know how to create a MapStyleOptions object. The type is unknown.

As this seems a common task to adopt the map (at least slighty) to your apps visual design, it would be good to have it in direct access.

Don't hesitate to contact me, if I can help anyhow. Not experienced in plugin development though, but keen to learn.

**Comment by dapriett** [comment]
Yes, we don't have support for styling the map directly in the plugin yet.

For Android, you should be able to create a MapStyleOptions object like so:

```
var jsonString = '{}'; // add style json here as string, or use Nativescript's file-system api to load from file
var styleOptions = new com.google.android.gms.maps.model.MapStyleOptions(jsonString);
gMap.setMapStyle(styleOptions)
```

**Comment by tviel** [comment]
Hi. Thx for your fast reply. 

Your proposal works as intended. How would that be integrated in the plugin? AFAIK, you write javascript files per platform (and in addition typescript def files), but I cant find any JS files in the plugin directory (below node_modules) for nativescript-google-maps-sdk.

**Comment by dapriett** [comment]
Great, thanks @nickcoury!
