### ISSUE TITLE
Service exited due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by zartheman** [dapriett/nativescript-google-maps-sdk#90]
Hi there,

I am trying to render a basic map on ios, using angular2 + nativescript. I followed all of the installation instructions and at run time, I am getting a segmentation fault 11 error. Any ideas how to resolve this error and render a basic map?

I am running tns-core-modules version 2.3 and xcode 7.2.

page.html

```
<StackLayout>
  <GridLayout>
    <MapView (mapReady)="onMapReady($event)"></MapView>
  </GridLayout>
</StackLayout>
```

page.component.ts

```
import { Component, ViewChild, ElementRef } from '@angular/core';
import { registerElement } from "nativescript-angular/element-registry";

// Important - must register MapView plugin in order to use in Angular templates
registerElement("MapView", () => require("nativescript-google-maps-sdk").MapView);


@Component({
  selector: 'page-login',
  templateUrl: './component/pages/page.html'
})
export class LoginComponent {

  @ViewChild("MapView") mapView: ElementRef;

  //Map events
  onMapReady = (event) => {
    console.log("Map Ready");
  };
}

```

To emulate the app I tried both:

```
tns livesync ios --watch --emulator 
```

and 

```
tns run ios --emulator
```

Note, removing the top two registerElement lines from the component (the import and the require lines), resolves the segmentation fault 11 error, however, these lines are required to load the map.

I also tried removing ios as a platform and re-adding it. I tried removing node_modules and then reinstalling all dependencies -- same outcome.

I appreciate any help, thanks in advance!

**Comment by nickcoury** [comment]
Did you set up the iOS api key? I recommend trying out the sample project first and see if you can get that to build.

Or if you want to use Angular 2, I put together a sample app using this plugin you can try too: https://github.com/nickcoury/nativescript-maps-app

If you can't get any of those to work, it's possible it's an issue with your Nativescript setup, or a plugin it is using like CocoaPods.  Running `tns doctor` from the command line might reveal an issue with that.

**Comment by zartheman** [comment]
Hi Nick,

Thanks for the reply. I was able to resolve the issue by adding the iOS api key as suggested and rebuilding the project. Thanks for the help!
