### ISSUE TITLE
Setting the amount detail in the map

### ISSUE THREAD

**Issue by zartheman** [dapriett/nativescript-google-maps-sdk#91]
When loading the map and setting the zoom, it seems the map is missing a lot of the details shown in the web version, as it is only showing country names and not showing streets. 

Is there a way to show as much detail as the default web version, so streets, neighborhoods, routes, etc are shown? For example: https://goo.gl/maps/WtTayYrfE4H2

This is what I currently have:

page.component.ts

```
 onMapReady = (args) => {
    var mapsModule = require("nativescript-google-maps-sdk");
    this.mapView = args.object;
    this.mapView.latitude = 8.5125665;
    this.mapView.longitude = -81.3038948;
    this.mapView.zoom = 20;

    var marker = new mapsModule.Marker();
    marker.position = mapsModule.Position.positionFromLatLng(28.3818941,-81.5768487);
    this.mapView.addMarker(marker);
  };

```

page.html

```
<GridLayout>
  <MapView (mapReady)="onMapReady($event)"></MapView>
</GridLayout>

```

**Comment by dapriett** [comment]
Hi @zartheman - this will be solved by issue #89, @nickcoury is working the feature.  Most of those details can be configured through the styles - like so https://mapstyle.withgoogle.com/

Closing this issue in favor of the other one.
