### ISSUE TITLE
Cannot read property 'android' of undefined

### ISSUE THREAD

**Issue by shadowzick** [dapriett/nativescript-google-maps-sdk#94]
Hi i'm getting this error:

JS: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
JS: EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'android'
of undefined
JS: ORIGINAL STACKTRACE:
JS: Error: Uncaught (in promise): TypeError: Cannot read property 'android' of undefined
JS:     at resolvePromise (/data/data/org.nativescript.groceries/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:416:31)
JS:     at /data/data/org.nativescript.groceries/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:393:13
JS:     at ZoneDelegate.invoke (/data/data/org.nativescript.groceries/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:190:28)
JS:     at Object.NgZoneImpl.inner.inner.fork.onInvoke (/data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js:6242:41)
JS:     at ZoneDelegate.invoke (/data/data/org.nativescript.groceries/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:189:34)
JS:     at Zone.run (/data/data/org.nativescript.groceries/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:83:43)
JS:     at /data/data/org.nativescript.groceries/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:449:57
JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.groceries/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:223:37)
JS:     at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (/data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js:6233:41)
JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.groceries/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:222:42)
JS: Unhandled Promise rejection: Cannot read property 'android' of undefined ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'android' of undefined TypeError: Cannot read property 'android' of undefined

I tried this; https://github.com/dapriett/nativescript-google-maps-sdk/issues/57

But it didn't seem to work. I'm using windows. Thanks

**Comment by shadowzick** [comment]
help!

**Comment by ghbakhtiari** [comment]
i've come to exactly the same error , what is it?

**Comment by ghbakhtiari** [comment]
for me it only happens when i'm running on the emulator. on device it works

**Comment by dapriett** [comment]
If you're having an issue with Android emulator, you're probably missing the Google Play service.  Look here https://www.genymotion.com/help/desktop/faq/#google-play-services

**Comment by shadowzick** [comment]
I got the issue from the device not the emulator, also I already installed the google play service.

**Comment by sktzoootech** [comment]
Any solution to this issue? This happens on my device as well.

**Comment by TheDemonMahesh** [comment]
comment the following code in qrcode.js 

// if (this._android && this._android >= 2.1) {
	    // 	var factor = 1 / window.devicePixelRatio;
	    //     var drawImage = CanvasRenderingContext2D.prototype.drawImage;
	    // 	CanvasRenderingContext2D.prototype.drawImage = function (image, sx, sy, sw, sh, dx, dy, dw, dh) {
	    // 		if (("nodeName" in image) && /img/i.test(image.nodeName)) {
		//         	for (var i = arguments.length - 1; i >= 1; i--) {
		//             	arguments[i] = arguments[i] * factor;
		//         	}
	    // 		} else if (typeof dw == "undefined") {
	    // 			arguments[1] *= factor;
	    // 			arguments[2] *= factor;
	    // 			arguments[3] *= factor;
	    // 			arguments[4] *= factor;
	    // 		}

	    //     	drawImage.apply(this, arguments);
	    // 	};
		// }

it may works check it for web applications
