### ISSUE TITLE
Can't find variable GMSMapViewDelegate

### ISSUE THREAD

**Issue by Hurinj** [dapriett/nativescript-google-maps-sdk#96]
Hello, 
I am new using NativeScript (I come from Cordova)
When I try to show the page where I have my google map I got this error in my console : 

`CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:344:22: Error: Uncaught (in promise): Error: Error in ./ListComponent class ListComponent - inline template:2:8 caused by: Could not load view for: MapView.ReferenceError: Can't find variable: GMSMapViewDelegate`

Cocoapods is installed...

My main  : 
```

"use strict";
if(application.ios) {
  GMSServices.provideAPIKey("mykey");
}
var platform_1 = require("nativescript-angular/platform");
var app_module_1 = require("./app.module");
platform_1.platformNativeScriptDynamic().bootstrapModule(app_module_1.AppModule);

```

the component : 

```
import {Component, ElementRef, ViewChild} from '@angular/core';
import {registerElement} from "nativescript-angular/element-registry";

// Important - must register MapView plugin in order to use in Angular templates
registerElement("MapView", () => require("nativescript-google-maps-sdk").MapView);


@Component({
    selector: 'list',
    template: `
    <GridLayout>
        <MapView (mapReady)="onMapReady($event)"></MapView>
    </GridLayout>
    `
})
export class ListComponent {

    @ViewChild("MapView") mapView: ElementRef;

    //Map events
    onMapReady = (event) => {
        console.log("Map Ready");
    };
}
```

**Comment by Hurinj** [comment]
Well now  I have this ... :  when i build 

```
[!] Unable to find a specification for `GoogleMaps`
Processing node_modules failed. Error: Command pod failed with exit code 1
```

**Comment by dapriett** [comment]
Run `tns doctor` - you probably don't have cocoapods installed https://docs.nativescript.org/plugins/cocoapods#install-cocoapods

**Comment by Hurinj** [comment]
Ok thank you, 
so I just did  `sudo gem install cocoapods`
after that I have again the same error. I tried to do `pod 'GoogleMaps'` but without success.
Do I need to Wrap the Library as NativeScript Plugin and create the json as they said ??
