### ISSUE TITLE
Adding elements above the map like slide menu ?

### ISSUE THREAD

**Issue by Hurinj** [dapriett/nativescript-google-maps-sdk#97]
All is in the question, I don't if it is possible with NativeScript Core like in cordova.
Is there any tutorial ?

I found this https://github.com/dapriett/nativescript-google-maps-sdk/issues/11, it does work but seems to disable the map isn't it ?

Thank you.

**Comment by nickcoury** [comment]
You should be able to add the MapView into any Nativescript app with any UI you'd like.  Unlike Cordova, Nativescript uses all native controls so there's no issue mixing your UI with plugins.

This uses Angular 2, but you can see an example of using the plugin with custom UI (a side drawer) here: https://github.com/nickcoury/nativescript-maps-app

If you need a tutorial for creating a Nativescript UI, I would refer to the official Telerik documentation and examples: https://docs.nativescript.org/tutorial/chapter-0

**Comment by Hurinj** [comment]
Thank you very much it is really helpful. 
Do you know if there is an example of the same kind with angular 1 and javascript?

**Comment by nickcoury** [comment]
Nativescript isn't actually compatible with Angular 1.  You can use the traditional Nativescript API which does use Javascript (linked earlier).  If you want to use Angular 2 with Typescript there's a tutorial here: https://docs.nativescript.org/tutorial/ng-chapter-0
